/* ============================================================
 data.js — costanti statiche v6.3
 Abitudini, statistiche, ranghi, quest pool, bestiario (190),
 equipaggiamento (30x6 slot), reliquie/tesori (100), negozio
 ============================================================ */

/* ── App info ── */
export const APP_VERSION = "6.3";
export const APP_RELEASE = "16/06/2026";
export const APP_DEV = "djiglio.ai";

/* ── Abitudini (11) ── */
export const HABITS = [
 { id:"allenamento", label:"Allenamento", icon:"", stat:"forza", color:"#dc2626" },
 { id:"passi", label:"7000 Passi", icon:"", stat:"velocita", color:"#0ea5e9" },
 { id:"stretching", label:"Stretching", icon:"", stat:"destrezza", color:"#10b981" },
 { id:"piegamenti", label:"Piegamenti", icon:"", stat:"critico", color:"#f97316" },
 { id:"enigmistica", label:"Enigmistica", icon:"", stat:"furtivita", color:"#8b5cf6" },
 { id:"dieta", label:"Dieta", icon:"", stat:"costituzione", color:"#84cc16" },
 { id:"meditazione", label:"Meditazione", icon:"", stat:"guarigione", color:"#06b6d4" },
 { id:"lettura", label:"Lettura", icon:"", stat:"fortuna", color:"#d97706" },
 { id:"sonno", label:"8 Ore di Sonno", icon:"", stat:"sopravvivenza",color:"#4f46e5" },
 { id:"studio", label:"Studio", icon:"", stat:"pianificazione",color:"#0891b2" },
 { id:"lingue", label:"Lingue", icon:"", stat:"carisma", color:"#be185d" },
];

/* ── Statistiche dell'eroe ── */
export const STAT_DEFS = [
  { id:"forza",         icon:"FOR", label:"FORZA",         habit:"allenamento",  desc:"Danno per colpo",             formula: lv => lv*3+5 },
  { id:"velocita",      icon:"VEL", label:"VELOCITÀ",      habit:"passi",        desc:"Iniziativa in combattimento",  formula: lv => lv*3+5 },
  { id:"destrezza",     icon:"DES", label:"DESTREZZA",     habit:"stretching",   desc:"% schivata colpi",             formula: lv => Math.min(60, lv*2+2) },
  { id:"critico",       icon:"CRI", label:"CRITICO",       habit:"piegamenti",   desc:"% colpi critici (x2)",         formula: lv => Math.min(50, lv*2+2) },
  { id:"furtivita",     icon:"FUR", label:"FURTIVITÀ",     habit:"enigmistica",  desc:"% riuscita fuga",              formula: lv => Math.min(85, lv*4+10) },
  { id:"costituzione",  icon:"COS", label:"COSTITUZIONE",  habit:"dieta",        desc:"PV massimi",           formula: lv => 50+lv*12 },
  { id:"guarigione",    icon:"GUA", label:"GUARIGIONE",    habit:"meditazione",  desc:"Minuti per +1 PV",             formula: lv => Math.max(1, 8-Math.floor(lv/3)) },
  { id:"fortuna",       icon:"LUC", label:"FORTUNA",       habit:"lettura",      desc:"Bonus bottino missioni",       formula: lv => lv },
  { id:"sopravvivenza", icon:"SOP", label:"SOPRAVVIVENZA", habit:"sonno",        desc:"PA massimi",         formula: lv => 5+lv*2 },
  { id:"pianificazione",icon:"PIA", label:"PIANIFICAZIONE",habit:"studio",       desc:"Minuti per +1 PA",                formula: lv => Math.max(1, 6-Math.floor(lv/4)) },
  { id:"carisma",       icon:"CAR", label:"CARISMA",       habit:"lingue",       desc:"% sconto al negozio",          formula: lv => Math.min(40, lv*2) },
];

/* ── Ranghi ── */
export const rankTitles = [
 { r:0, t:"MENDICANTE" }, { r:2, t:"VAGABONDO" }, { r:5, t:"PASTORE" },
 { r:8, t:"CONTADINO" }, { r:11, t:"FABBRO" }, { r:14, t:"RECLUTA" },
 { r:18, t:"RAMINGO" }, { r:22, t:"MERCENARIO" }, { r:26, t:"SCUDIERO" },
 { r:30, t:"SPADACCINO" }, { r:35, t:"GLADIATORE" }, { r:40, t:"VETERANO" },
 { r:45, t:"PALADINO" }, { r:50, t:"CAVALIERE" }, { r:55, t:"CAMPIONE" },
 { r:60, t:"GENERALE" }, { r:65, t:"BARONE" }, { r:70, t:"VISCONTE" },
 { r:75, t:"CONTE" }, { r:80, t:"MARCHESE" }, { r:85, t:"DUCA" },
 { r:90, t:"ARCIDUCA" }, { r:95, t:"PRINCIPE" }, { r:100, t:"RE" },
 { r:110, t:"IMPERATORE" }, { r:120, t:"SEMIDIO" }, { r:140, t:"ASCESO" },
];

export const titleMetalColors = {
 "MENDICANTE":"#6b6b78","VAGABONDO":"#7a6e5a","PASTORE":"#7d8c72","CONTADINO":"#8c7e62",
 "FABBRO":"#9e6840","RECLUTA":"#7090a8","RAMINGO":"#707e90","MERCENARIO":"#b09030",
 "SCUDIERO":"#8098b8","SPADACCINO":"#b89858","GLADIATORE":"#c07828","VETERANO":"#9098a0",
 "PALADINO":"#c0b090","CAVALIERE":"#a0b8cc","CAMPIONE":"#c8a828","GENERALE":"#c09040",
 "BARONE":"#a08868","VISCONTE":"#9878b8","CONTE":"#a09050","MARCHESE":"#7888a8",
 "DUCA":"#c0a870","ARCIDUCA":"#c8b840","PRINCIPE":"#d0b040","RE":"#d8c060",
 "IMPERATORE":"#e0d090","SEMIDIO":"#b8d8e8","ASCESO":"#e8e8f0",
};

export const avatarPalettes = {
 "MENDICANTE":"#5a5a6a","VAGABONDO":"#6b5e4a","PASTORE":"#7a8c6e","CONTADINO":"#8c7a5a",
 "FABBRO":"#a0522d","RECLUTA":"#7a9aaa","RAMINGO":"#6e7a8a","MERCENARIO":"#b8860b",
 "SCUDIERO":"#8faacc","SPADACCINO":"#c0a060","GLADIATORE":"#cc7722","VETERANO":"#9aaba8",
 "PALADINO":"#d4c5a9","CAVALIERE":"#b0c4de","CAMPIONE":"#d4af37","GENERALE":"#c8a050",
 "BARONE":"#a09070","VISCONTE":"#b8a0d0","CONTE":"#c0b080","MARCHESE":"#90a0b8",
 "DUCA":"#d8c090","ARCIDUCA":"#e8d080","PRINCIPE":"#f0d890","RE":"#f5e0a0",
 "IMPERATORE":"#f8ead0","SEMIDIO":"#e8f4f8","ASCESO":"#ffffff",
};

export const nobleMantle = {
 "BARONE": {base:"#3a1520",hi:"#6a2838",trim:"#8a3a50"},
 "VISCONTE": {base:"#20103a",hi:"#482070",trim:"#7040a0"},
 "CONTE": {base:"#0a2414",hi:"#165030",trim:"#2a7848"},
 "MARCHESE": {base:"#0c1830",hi:"#1a3460",trim:"#2a5090"},
 "DUCA": {base:"#080c24",hi:"#101850",trim:"#1c2e80"},
 "ARCIDUCA": {base:"#180828",hi:"#3a1060",trim:"#6020a0"},
 "PRINCIPE": {base:"#280808",hi:"#601010",trim:"#901a1a"},
 "RE": {base:"#140520",hi:"#300c50",trim:"#5a1888"},
 "IMPERATORE":{base:"#04040c",hi:"#181830",trim:"#303060"},
};

/* ══════════════════════════════════════════════════════════
 POOL MISSIONI SETTIMANALI — 50 evoluzione + 50 mondo
══════════════════════════════════════════════════════════ */
export const QUEST_POOL_EVO = [
 // Abitudini singole
 {id:"e01",text:"Atleta Instancabile", desc:"Completa Allenamento 4 volte", target:4, type:"habit", habit:"allenamento"},
 {id:"e02",text:"Maratoneta", desc:"Completa 7000 Passi 4 volte", target:4, type:"habit", habit:"passi"},
 {id:"e03",text:"Corpo Flessibile", desc:"Completa Stretching 5 volte", target:5, type:"habit", habit:"stretching"},
 {id:"e04",text:"Guerriero di Ferro", desc:"Completa Piegamenti 5 volte", target:5, type:"habit", habit:"piegamenti"},
 {id:"e05",text:"Mente Acuta", desc:"Completa Enigmistica 6 volte", target:6, type:"habit", habit:"enigmistica"},
 {id:"e06",text:"Nutrizione Reale", desc:"Completa Dieta 6 volte", target:6, type:"habit", habit:"dieta"},
 {id:"e07",text:"Monaco Zen", desc:"Completa Meditazione 5 volte", target:5, type:"habit", habit:"meditazione"},
 {id:"e08",text:"Topo di Biblioteca", desc:"Completa Lettura 5 volte", target:5, type:"habit", habit:"lettura"},
 {id:"e09",text:"Letargo Profondo", desc:"Completa 8 Ore di Sonno 5 volte", target:5, type:"habit", habit:"sonno"},
 {id:"e10",text:"Studioso Erudito", desc:"Completa Studio 4 volte", target:4, type:"habit", habit:"studio"},
 {id:"e11",text:"Poliglotta", desc:"Completa Lingue 6 volte", target:6, type:"habit", habit:"lingue"},
 // Multi-habit
 {id:"e12",text:"Mente e Corpo", desc:"Completa 15 abitudini totali", target:15, type:"total"},
 {id:"e13",text:"Costanza Eterna", desc:"Completa 20 abitudini totali", target:20, type:"total"},
 {id:"e14",text:"Maestro Kaizen", desc:"Completa 28 abitudini totali", target:28, type:"total"},
 {id:"e15",text:"Atleta Completo", desc:"Completa Allenamento e Passi 3 volte", target:6, type:"multi", habits:["allenamento","passi"]},
 {id:"e16",text:"Corpo Perfetto", desc:"Completa Piegamenti e Stretching 4x", target:8, type:"multi", habits:["piegamenti","stretching"]},
 {id:"e17",text:"Mente Sana", desc:"Completa Studio ed Enigmistica 4x", target:8, type:"multi", habits:["studio","enigmistica"]},
 {id:"e18",text:"Anima Pura", desc:"Completa Meditazione e Lettura 4x", target:8, type:"multi", habits:["meditazione","lettura"]},
 {id:"e19",text:"Ritmo Perfetto", desc:"Completa Sonno e Dieta 5 volte", target:10, type:"multi", habits:["sonno","dieta"]},
 {id:"e20",text:"Tuttofare", desc:"Completa ogni abitudine almeno 1 volta",target:11, type:"all_once"},
 {id:"e21",text:"Giornata Perfetta", desc:"Completa tutte le 11 abitudini in 1 giorno",target:1,type:"perfect_day"},
 {id:"e22",text:"Due Giornate Perfette", desc:"Ottieni 2 giornate perfette", target:2, type:"perfect_day"},
 {id:"e23",text:"Campione Mattutino", desc:"Completa Allenamento 6 volte", target:6, type:"habit", habit:"allenamento"},
 {id:"e24",text:"Nomade Instancabile", desc:"Completa 7000 Passi 6 volte", target:6, type:"habit", habit:"passi"},
 {id:"e25",text:"Ginnasta", desc:"Completa Stretching 7 volte", target:7, type:"habit", habit:"stretching"},
 {id:"e26",text:"100 Piegamenti al Giorno",desc:"Completa Piegamenti 7 volte", target:7, type:"habit", habit:"piegamenti"},
 {id:"e27",text:"Enigmista Professionista",desc:"Completa Enigmistica 7 volte", target:7, type:"habit", habit:"enigmistica"},
 {id:"e28",text:"Nutrizionista Rigoroso", desc:"Completa Dieta 7 volte", target:7, type:"habit", habit:"dieta"},
 {id:"e29",text:"Guru della Pace", desc:"Completa Meditazione 7 volte", target:7, type:"habit", habit:"meditazione"},
 {id:"e30",text:"Lettore Vorace", desc:"Completa Lettura 7 volte", target:7, type:"habit", habit:"lettura"},
 {id:"e31",text:"Ipnos Benedetto", desc:"Completa 8 Ore di Sonno 7 volte", target:7, type:"habit", habit:"sonno"},
 {id:"e32",text:"Accademico", desc:"Completa Studio 7 volte", target:7, type:"habit", habit:"studio"},
 {id:"e33",text:"Ambasciatore", desc:"Completa Lingue 7 volte", target:7, type:"habit", habit:"lingue"},
 {id:"e34",text:"Settimana di Fuoco", desc:"Completa 35 abitudini questa settimana",target:35, type:"total"},
 {id:"e35",text:"Leggenda Vivente", desc:"Completa 44 abitudini questa settimana",target:44, type:"total"},
 {id:"e36",text:"Forza Bruta", desc:"Completa Allenamento 7 volte", target:7, type:"habit", habit:"allenamento"},
 {id:"e37",text:"Corridore Solitario", desc:"Completa 7000 Passi 7 volte", target:7, type:"habit", habit:"passi"},
 {id:"e38",text:"Mente di Cristallo", desc:"Completa 5 diverse abitudini almeno 3x",target:15, type:"variety5"},
 {id:"e39",text:"Equilibrio Cosmico", desc:"Completa tutte le 11 abitudini 2 volte",target:22, type:"all_twice"},
 {id:"e40",text:"Guerriero Olistico", desc:"Completa abitudini fisiche 15 volte", target:15, type:"multi", habits:["allenamento","passi","piegamenti","stretching"]},
 {id:"e41",text:"Studioso Completo", desc:"Completa abitudini mentali 15 volte", target:15, type:"multi", habits:["studio","enigmistica","lettura","lingue"]},
 {id:"e42",text:"Corpo Sano", desc:"Completa abitudini salute 15 volte", target:15, type:"multi", habits:["dieta","meditazione","sonno"]},
 {id:"e43",text:"Primo Passo", desc:"Completa 5 abitudini totali", target:5, type:"total"},
 {id:"e44",text:"Inizio Promettente", desc:"Completa 10 abitudini totali", target:10, type:"total"},
 {id:"e45",text:"Disciplina di Acciaio", desc:"Completa Allenamento e Piegamenti 5x", target:10, type:"multi", habits:["allenamento","piegamenti"]},
 {id:"e46",text:"Mente Lucida", desc:"Completa Studio e Lettura 5x", target:10, type:"multi", habits:["studio","lettura"]},
 {id:"e47",text:"Spirito Libero", desc:"Completa Meditazione e Lingue 4x", target:8, type:"multi", habits:["meditazione","lingue"]},
 {id:"e48",text:"Vitalità Massima", desc:"Completa Dieta e Sonno 6x", target:12, type:"multi", habits:["dieta","sonno"]},
 {id:"e49",text:"Velocista", desc:"Completa 7000 Passi e Stretching 5x", target:10, type:"multi", habits:["passi","stretching"]},
 {id:"e50",text:"Campione Assoluto", desc:"Completa tutte le 11 abitudini 3 volte",target:33, type:"all_three"},
];

export const QUEST_POOL_WORLD = [
 {id:"w01",text:"Cacciatore di Bestie", desc:"Sconfiggi 3 nemici", target:3, type:"kills_any"},
 {id:"w02",text:"Sterminatore", desc:"Sconfiggi 5 nemici", target:5, type:"kills_any"},
 {id:"w03",text:"Signore della Guerra", desc:"Sconfiggi 10 nemici", target:10, type:"kills_any"},
 {id:"w04",text:"Cacciatore di Goblin", desc:"Sconfiggi 3 Goblin", target:3, type:"kills_tag", tag:"goblin"},
 {id:"w05",text:"Sterminatore di Non Morti",desc:"Sconfiggi 3 non-morti", target:3, type:"kills_tag", tag:"nonmorto"},
 {id:"w06",text:"Ammazza Draghi", desc:"Sconfiggi 2 draghi", target:2, type:"kills_tag", tag:"drago"},
 {id:"w07",text:"Cacciatore di Lupi", desc:"Sconfiggi 4 lupi o licantropi", target:4, type:"kills_tag", tag:"lupo"},
 {id:"w08",text:"Uccisore di Troll", desc:"Sconfiggi 3 troll", target:3, type:"kills_tag", tag:"troll"},
 {id:"w09",text:"Collezionista", desc:"Raccogli oggetti per valore totale 50 den.", target:50, type:"loot_value"},
 {id:"w10",text:"Avventuriero Ricco", desc:"Raccogli oggetti per valore totale 100 den.",target:100, type:"loot_value"},
 {id:"w11",text:"Mercante di Tesori", desc:"Raccogli oggetti per valore totale 200 den.",target:200, type:"loot_value"},
 {id:"w12",text:"Esploratore", desc:"Parti in missione 5 volte", target:5, type:"missions_total"},
 {id:"w13",text:"Veterano del Campo", desc:"Parti in missione 10 volte", target:10, type:"missions_total"},
 {id:"w14",text:"Eroe Leggendario", desc:"Parti in missione 15 volte", target:15, type:"missions_total"},
 {id:"w15",text:"Fortunato", desc:"Scopri 3 tesori", target:3, type:"discoveries"},
 {id:"w16",text:"Trovatore", desc:"Scopri 6 tesori", target:6, type:"discoveries"},
 {id:"w17",text:"Cerca Reliquie", desc:"Trova 2 reliquie", target:2, type:"relics_found"},
 {id:"w18",text:"Guardiano delle Reliquie",desc:"Trova 3 reliquie", target:3, type:"relics_found"},
 {id:"w19",text:"Fuggitivo", desc:"Fuggi da un combattimento", target:1, type:"fled"},
 {id:"w20",text:"Sopravvissuto", desc:"Fuggi da 3 combattimenti", target:3, type:"fled"},
 {id:"w21",text:"Sterminatore di Vampiri", desc:"Sconfiggi 2 vampiri", target:2, type:"kills_tag", tag:"vampiro"},
 {id:"w22",text:"Ammazza Orchi", desc:"Sconfiggi 4 ogre o troll", target:4, type:"kills_tag", tag:"ogre"},
 {id:"w23",text:"Cacciatore di Demoni", desc:"Sconfiggi 2 demoni", target:2, type:"kills_tag", tag:"demone"},
 {id:"w24",text:"Piccolo Tesoro", desc:"Accumula 80 denari", target:80, type:"denari_earned"},
 {id:"w25",text:"Grande Fortuna", desc:"Accumula 150 denari totali guadagnati", target:150, type:"denari_earned"},
 {id:"w26",text:"Nemici Potenti", desc:"Sconfiggi 2 nemici di livello 50+", target:2, type:"kills_lvl", minLvl:50},
 {id:"w27",text:"Coraggioso", desc:"Sconfiggi 1 nemico di livello 80+", target:1, type:"kills_lvl", minLvl:80},
 {id:"w28",text:"Leggenda", desc:"Sconfiggi 1 nemico di livello 100+", target:1, type:"kills_lvl", minLvl:100},
 {id:"w29",text:"Predatore Seriale", desc:"Sconfiggi 3 nemici umanoidi", target:3, type:"kills_human"},
 {id:"w30",text:"Cacciatore di Bestie Rare",desc:"Sconfiggi 5 nemici umanoidi", target:5, type:"kills_human"},
 {id:"w31",text:"Razziatore", desc:"Ottieni equipaggiamento da 3 nemici", target:3, type:"equip_looted"},
 {id:"w32",text:"Armaiolo di Guerra", desc:"Ottieni equipaggiamento da 6 nemici", target:6, type:"equip_looted"},
 {id:"w33",text:"Cacciatore di Scheletri", desc:"Sconfiggi 4 scheletri", target:4, type:"kills_tag", tag:"scheletro"},
 {id:"w34",text:"Sterminatore di Ragni", desc:"Sconfiggi 3 ragni", target:3, type:"kills_tag", tag:"ragno"},
 {id:"w35",text:"Nemico dei Bandit", desc:"Sconfiggi 4 banditi", target:4, type:"kills_tag", tag:"bandito"},
 {id:"w36",text:"Puro Terrore", desc:"Vinci 5 combattimenti consecutivi", target:5, type:"win_streak"},
 {id:"w37",text:"Resistente", desc:"Sopravvivi con meno del 20% HP", target:1, type:"survived_low_hp"},
 {id:"w38",text:"Zona di Guerra", desc:"Combatti 8 volte", target:8, type:"combats_total"},
 {id:"w39",text:"Pacifista Armato", desc:"Completa 3 missioni senza perdere HP", target:3, type:"no_damage_missions"},
 {id:"w40",text:"Cacciatore di Teste", desc:"Sconfiggi 15 nemici totali", target:15, type:"kills_any"},
 {id:"w41",text:"Scopritore", desc:"Trova 4 oggetti rari (tier 4+)", target:4, type:"rare_finds"},
 {id:"w42",text:"Alchimista", desc:"Raccogli 5 oggetti diversi", target:5, type:"unique_finds"},
 {id:"w43",text:"Ammazza Golem", desc:"Sconfiggi 3 golem", target:3, type:"kills_tag", tag:"golem"},
 {id:"w44",text:"Cacciatore di Spiriti", desc:"Sconfiggi 3 spiriti o spettri", target:3, type:"kills_tag", tag:"spirito"},
 {id:"w45",text:"Distruttore di Elementali",desc:"Sconfiggi 2 elementali", target:2, type:"kills_tag", tag:"elementale"},
 {id:"w46",text:"Grande Esploratore", desc:"Parti in missione 20 volte", target:20, type:"missions_total"},
 {id:"w47",text:"Ricchissimo", desc:"Guadagna 300 denari in missioni", target:300, type:"denari_earned"},
 {id:"w48",text:"Terrore del Bestiario", desc:"Incontra 10 nemici diversi", target:10, type:"unique_enemies"},
 {id:"w49",text:"Sterminatore Totale", desc:"Sconfiggi 20 nemici", target:20, type:"kills_any"},
 {id:"w50",text:"Grande Cacciatore", desc:"Sconfiggi 1 nemico di livello 120+", target:1, type:"kills_lvl", minLvl:120},
];

/* ══════════════════════════════════════════════════════════
 IMMAGINI — percorsi standardizzati
 img/ranks/<titolo_minuscolo>.png — avatar per ogni rango (27 file)
 img/enemies/<id>.png — una per nemico (e001…e150)
 Se un file manca, il codice mostra il simbolo testuale.
══════════════════════════════════════════════════════════ */

/** Tutti i titoli/ranghi con il percorso immagine corrispondente */
export const RANK_IMG_MAP = {}; // popolato dopo rankTitles

/* ══════════════════════════════════════════════════════════
 EQUIPMENT POOL — 30 pezzi per slot (tier 1-10, 3 per tier)
 bonus: { stat, value } — stat in ["attacco","difesa","velocita","critico"]
══════════════════════════════════════════════════════════ */
function genEquip(slot, icon, tier, idx, name, bonusStat, bonusVal, desc, fonte) {
 // Prezzi bilanciati per tier (1-10):
 // Tier 1: 15-25 | Tier 2: 40-60 | Tier 3: 90-130
 // Tier 4: 180-240| Tier 5: 320-400 | Tier 6: 520-640
 // Tier 7: 780-960| Tier 8: 1100-1350| Tier 9: 1600-1950| Tier 10: 2400-2900
 const priceBase = [0, 20, 50, 110, 210, 360, 580, 870, 1220, 1750, 2650];
 const priceVar = [0, 6, 12, 24, 36, 50, 70, 96, 130, 200, 250];
 const prezzo = priceBase[tier] + (idx - 1) * priceVar[tier];
 return { id:`${slot[0]}${tier}${idx}`, slot, icon, tier, name, bonus:{[bonusStat]:bonusVal}, desc, prezzo, fonte: fonte||["negozio"] };
}

export const EQUIPMENT_POOL = [
 // ── ARMI (attacco) ──
 genEquip("arma","",1,1,"Bastone Nodoso", "attacco",2, "Un ramo robusto, meglio di niente",["negozio","esplorazione"]),
 genEquip("arma","",1,2,"Coltello Arrugginito","attacco",3, "La lama regge ancora",["negozio"]),
 genEquip("arma","",1,3,"Forcone da Contadino","attacco",3, "Tre punte, altrettante ferite",["esplorazione"]),
 genEquip("arma","",2,1,"Spada Corta", "attacco",5, "Affidabile nel corpo a corpo",["negozio"]),
 genEquip("arma","",2,2,"Ascia da Guerra", "attacco",6, "Pesante ma devastante",["negozio","loot"]),
 genEquip("arma","",2,3,"Mazza Ferrata", "attacco",5, "Spezza armature e ossa",["negozio"]),
 genEquip("arma","",3,1,"Spada Lunga", "attacco",9, "Equilibrio tra velocità e forza",["negozio","loot"]),
 genEquip("arma","",3,2,"Alabarda", "attacco",10,"Tiene il nemico a distanza",["negozio"]),
 genEquip("arma","",3,3,"Spada del Gladiatore", "attacco",11,"Forgiata nell'arena",["loot"]),
 genEquip("arma","",4,1,"Lama Oscura", "attacco",14,"Assorbe la luce attorno a sé",["negozio","loot"]),
 genEquip("arma","",4,2,"Spada del Campione", "attacco",16,"Apparteneva a un eroe caduto",["loot"]),
 genEquip("arma","",4,3,"Falce dell'Arciduca", "attacco",17,"Falcia tutto ciò che tocca",["loot"]),
 genEquip("arma","",5,1,"Lama Infuocata", "attacco",20,"Arde di fiamme eterne",["loot"]),
 genEquip("arma","",5,2,"Spada di Diamante", "attacco",22,"Tagliente come la verità",["loot"]),
 genEquip("arma","",5,3,"Tridente del Mare", "attacco",21,"Forgiata negli abissi",["loot"]),
 genEquip("arma","",6,1,"Lama del Fulmine", "attacco",25,"Colpisce alla velocità del tuono",["loot"]),
 genEquip("arma","",6,2,"Falce Lunare", "attacco",27,"Brilla sotto la luna piena",["loot"]),
 genEquip("arma","",6,3,"Spada di Ghiaccio", "attacco",26,"Congela il sangue dei nemici",["loot"]),
 genEquip("arma","",7,1,"Lama Velenosa", "attacco",31,"Avvelenata con estratti rari",["loot"]),
 genEquip("arma","",7,2,"Osso di Titanio", "attacco",33,"Forgiata dall'osso di un titano",["loot"]),
 genEquip("arma","",7,3,"Zanna del Drago", "attacco",32,"Strappata da un drago antico",["loot"]),
 genEquip("arma","",8,1,"Scettro Regale", "attacco",37,"Simbolo di potere assoluto",["loot"]),
 genEquip("arma","",8,2,"Spada delle Stelle", "attacco",39,"Caduta dal cielo",["loot"]),
 genEquip("arma","",8,3,"Bastone Arcano", "attacco",38,"Canalizza energia mistica",["loot"]),
 genEquip("arma","",9,1,"Lama Meteoritica", "attacco",44,"Forgiata da metallo cosmico",["loot"]),
 genEquip("arma","",9,2,"Falce della Morte", "attacco",46,"Solo i più forti possono sollevarla",["loot"]),
 genEquip("arma","",9,3,"Spada dell'Oblio", "attacco",45,"Chi la tocca dimentica il timore",["loot"]),
 genEquip("arma","",10,1,"Lama dell'Asceso", "attacco",52,"Arma leggendaria primordiale",["loot"]),
 genEquip("arma","",10,2,"Spada del Re Eterno", "attacco",54,"Forgiata da un dio",["loot"]),
 genEquip("arma","",10,3,"Excalibur dell'Abisso", "attacco",53,"La lama definitiva",["loot"]),

 // ── ELMI (difesa) ──
 genEquip("elmo","",1,1,"Cappello di Paglia","difesa",1,"Protegge dal sole, non dalle spade",["negozio"]),
 genEquip("elmo","",1,2,"Cuffia di Cuoio", "difesa",1,"Semplice ma meglio di nulla",["negozio","esplorazione"]),
 genEquip("elmo","",1,3,"Fascia di Cuoio", "difesa",2,"Almeno copre la fronte",["esplorazione"]),
 genEquip("elmo","",2,1,"Elmo di Ferro", "difesa",3,"Protezione standard dei soldati",["negozio"]),
 genEquip("elmo","",2,2,"Elmo con Visiera", "difesa",4,"Copre anche il viso",["negozio","loot"]),
 genEquip("elmo","",2,3,"Casco Legionario", "difesa",3,"Stile romano, resistenza assoluta",["negozio"]),
 genEquip("elmo","",3,1,"Elmo del Cavaliere","difesa",6,"Inciso con stemmi nobiliari",["negozio","loot"]),
 genEquip("elmo","",3,2,"Elmo del Gladiatore","difesa",7,"La cresta lo rende inconfondibile",["loot"]),
 genEquip("elmo","",3,3,"Elmo a Visiera Piena","difesa",6,"Protegge ogni angolo del viso",["negozio"]),
 genEquip("elmo","",4,1,"Elmo Oscuro", "difesa",9,"Incute terrore nei nemici",["loot"]),
 genEquip("elmo","",4,2,"Elmo del Templare", "difesa",10,"Benedetto da ordini sacri",["loot"]),
 genEquip("elmo","",4,3,"Elmo del Generale", "difesa",9,"Portato in mille battaglie",["loot"]),
 genEquip("elmo","",5,1,"Elmo Infuocato", "difesa",12,"Arde di un fuoco eterno",["loot"]),
 genEquip("elmo","",5,2,"Elmo Glaciale", "difesa",13,"Freddo come l'inverno eterno",["loot"]),
 genEquip("elmo","",5,3,"Elmo Lunare", "difesa",12,"Brilla di luce argentata",["loot"]),
 genEquip("elmo","",6,1,"Elmo del Fulmine", "difesa",15,"Conduce l'energia degli dei",["loot"]),
 genEquip("elmo","",6,2,"Elmo del Drago", "difesa",16,"Fatto con le squame di un drago",["loot"]),
 genEquip("elmo","",6,3,"Elmo Velenoso", "difesa",15,"Avvelenato alla minima scalfitura",["loot"]),
 genEquip("elmo","",7,1,"Corona Guerriera", "difesa",19,"Corona e protezione in uno",["loot"]),
 genEquip("elmo","",7,2,"Elmo delle Stelle", "difesa",20,"Caduto dal firmamento",["loot"]),
 genEquip("elmo","",7,3,"Elmo Arcano", "difesa",19,"Protezione magica assoluta",["loot"]),
 genEquip("elmo","",8,1,"Elmo Meteorico", "difesa",23,"Forgiato da un meteorite",["loot"]),
 genEquip("elmo","",8,2,"Elmo di Diamante", "difesa",24,"Indistruttibile come il diamante",["loot"]),
 genEquip("elmo","",8,3,"Elmo dell'Oblio", "difesa",23,"Chi lo indossa non teme la morte",["loot"]),
 genEquip("elmo","",9,1,"Teschio del Titano", "difesa",27,"Rimosso da un titano sconfitto",["loot"]),
 genEquip("elmo","",9,2,"Elmo Primordiale", "difesa",29,"Esiste dall'alba dei tempi",["loot"]),
 genEquip("elmo","",9,3,"Elmo Cosmico", "difesa",28,"Protegge anche l'anima",["loot"]),
 genEquip("elmo","",10,1,"Corona di Ferro", "difesa",33,"Protezione regale assoluta",["loot"]),
 genEquip("elmo","",10,2,"Elmo dell'Asceso", "difesa",34,"Nessun colpo lo scalfisce",["loot"]),
 genEquip("elmo","",10,3,"Diadema Eterno", "difesa",33,"Forgiato prima del tempo",["loot"]),

 // ── SCUDI (difesa) ──
 genEquip("scudo","",1,1,"Tavola di Legno", "difesa",1,"Non durerà a lungo",["negozio"]),
 genEquip("scudo","",1,2,"Scudo di Cuoio", "difesa",2,"Leggero e manovrabile",["negozio","esplorazione"]),
 genEquip("scudo","",1,3,"Scudo di Paglia", "difesa",1,"Meglio di niente",["esplorazione"]),
 genEquip("scudo","",2,1,"Scudo Rotondo", "difesa",4,"Il classico scudo del soldato",["negozio"]),
 genEquip("scudo","",2,2,"Scudo a Goccia", "difesa",5,"Protegge anche le gambe",["negozio","loot"]),
 genEquip("scudo","",2,3,"Scudo Longobardo", "difesa",4,"Resistente e affidabile",["negozio"]),
 genEquip("scudo","",3,1,"Scudo del Paladino","difesa",7,"Benedetto da un ordine sacro",["negozio","loot"]),
 genEquip("scudo","",3,2,"Scudo Eraldico", "difesa",8,"Stemma di una casata caduta",["loot"]),
 genEquip("scudo","",3,3,"Scudo del Crociato","difesa",7,"Portato in mille crociate",["negozio"]),
 genEquip("scudo","",4,1,"Scudo del Generale","difesa",10,"Deviato mille colpi mortali",["loot"]),
 genEquip("scudo","",4,2,"Scudo Infuocato", "difesa",11,"Brucia chi osa toccarlo",["loot"]),
 genEquip("scudo","",4,3,"Scudo Glaciale", "difesa",10,"Congela i proiettili in volo",["loot"]),
 genEquip("scudo","",5,1,"Scudo del Fulmine", "difesa",13,"Conduce l'energia divina",["loot"]),
 genEquip("scudo","",5,2,"Scudo Lunare", "difesa",14,"Brilla di luce argentata",["loot"]),
 genEquip("scudo","",5,3,"Scudo del Drago", "difesa",13,"Squame di drago fuse insieme",["loot"]),
 genEquip("scudo","",6,1,"Scudo Velenoso", "difesa",16,"Avvelena chi lo colpisce",["loot"]),
 genEquip("scudo","",6,2,"Scudo di Diamante", "difesa",17,"Impossibile scalfirlo",["loot"]),
 genEquip("scudo","",6,3,"Scudo dell'Ombra", "difesa",16,"Si nasconde nell'oscurità",["loot"]),
 genEquip("scudo","",7,1,"Scudo Regale", "difesa",20,"Portato da un re leggendario",["loot"]),
 genEquip("scudo","",7,2,"Scudo delle Stelle","difesa",21,"Caduto dal cielo in fiamme",["loot"]),
 genEquip("scudo","",7,3,"Scudo Arcano", "difesa",20,"Assorbe la magia ostile",["loot"]),
 genEquip("scudo","",8,1,"Scudo Meteorico", "difesa",24,"Forgiato da metallo cosmico",["loot"]),
 genEquip("scudo","",8,2,"Scudo del Titano", "difesa",25,"Pesante come un titano",["loot"]),
 genEquip("scudo","",8,3,"Scudo dell'Oblio", "difesa",24,"Annulla qualsiasi danno",["loot"]),
 genEquip("scudo","",9,1,"Scudo Primordiale", "difesa",28,"Antico quanto il mondo",["loot"]),
 genEquip("scudo","",9,2,"Scudo Eterno", "difesa",30,"Non si è mai rotto",["loot"]),
 genEquip("scudo","",9,3,"Scudo Cosmico", "difesa",29,"Protegge anche i sogni",["loot"]),
 genEquip("scudo","",10,1,"Egida dell'Asceso","difesa",34,"Scudo cosmico indistruttibile",["loot"]),
 genEquip("scudo","",10,2,"Scudo del Re Eterno","difesa",35,"Portato dall'eroe dei tempi",["loot"]),
 genEquip("scudo","",10,3,"Bastione Divino", "difesa",34,"Dono degli dei",["loot"]),

 // ── CORAZZE (difesa) ──
 genEquip("corazza","",1,1,"Camicia di Cuoio", "difesa",2,"Indurisce col sale e il sudore",["negozio"]),
 genEquip("corazza","",1,2,"Giaco Imbottito", "difesa",2,"Assorbe i colpi con ovatta",["negozio","esplorazione"]),
 genEquip("corazza","",1,3,"Veste di Stracci", "difesa",1,"Almeno copre qualcosa",["esplorazione"]),
 genEquip("corazza","",2,1,"Cotta di Maglia", "difesa",5,"Anelli di ferro intrecciati",["negozio"]),
 genEquip("corazza","",2,2,"Corazza a Lamelle", "difesa",6,"Protezione mobile e robusta",["negozio","loot"]),
 genEquip("corazza","",2,3,"Giaco di Ferro", "difesa",5,"Pesante ma efficace",["negozio"]),
 genEquip("corazza","",3,1,"Corazza del Guerriero","difesa",9,"Rune di protezione incise",["negozio","loot"]),
 genEquip("corazza","",3,2,"Corazza del Veterano","difesa",10,"Ogni ammaccatura è una storia",["loot"]),
 genEquip("corazza","",3,3,"Corazza Legionaria","difesa",9,"Resistente alle legioni",["negozio"]),
 genEquip("corazza","",4,1,"Corazza dell'Imperatore","difesa",13,"Regge l'assalto di un esercito",["loot"]),
 genEquip("corazza","",4,2,"Corazza Infuocata", "difesa",14,"Arde di un fuoco interiore",["loot"]),
 genEquip("corazza","",4,3,"Corazza Glaciale", "difesa",13,"Fredda come l'inverno",["loot"]),
 genEquip("corazza","",5,1,"Corazza del Fulmine","difesa",16,"Carica elettrica permanente",["loot"]),
 genEquip("corazza","",5,2,"Corazza Lunare", "difesa",17,"Brilla d'argento alla luna",["loot"]),
 genEquip("corazza","",5,3,"Scaglia del Drago", "difesa",16,"Squame di un drago antico",["loot"]),
 genEquip("corazza","",6,1,"Corazza Velenosa", "difesa",20,"Avvelena chi la colpisce",["loot"]),
 genEquip("corazza","",6,2,"Corazza di Diamante","difesa",21,"Indistruttibile come il diamante",["loot"]),
 genEquip("corazza","",6,3,"Corazza dell'Ombra", "difesa",20,"Si dissolve nell'oscurità",["loot"]),
 genEquip("corazza","",7,1,"Corazza Regale", "difesa",24,"Indossata solo dai re",["loot"]),
 genEquip("corazza","",7,2,"Corazza Stellare", "difesa",25,"Caduta da un meteorite",["loot"]),
 genEquip("corazza","",7,3,"Corazza Arcana", "difesa",24,"Assorbe energia magica",["loot"]),
 genEquip("corazza","",8,1,"Corazza Meteoritica","difesa",28,"Forgiata da un meteorite",["loot"]),
 genEquip("corazza","",8,2,"Corazza del Titano", "difesa",29,"Pesa quanto un titano",["loot"]),
 genEquip("corazza","",8,3,"Corazza dell'Oblio", "difesa",28,"Annulla qualsiasi danno",["loot"]),
 genEquip("corazza","",9,1,"Corazza Primordiale","difesa",33,"Antica quanto il mondo",["loot"]),
 genEquip("corazza","",9,2,"Corazza Eterna", "difesa",35,"Non si è mai rotta",["loot"]),
 genEquip("corazza","",9,3,"Corazza Cosmica", "difesa",34,"Protegge corpo e spirito",["loot"]),
 genEquip("corazza","",10,1,"Armatura Primordiale","difesa",40,"Plasmata prima del mondo",["loot"]),
 genEquip("corazza","",10,2,"Corazza dell'Asceso","difesa",42,"Indossata dal più grande",["loot"]),
 genEquip("corazza","",10,3,"Veste degli Dei", "difesa",41,"Tessuta con fili divini",["loot"]),

 // ── GAMBALI (difesa) ──
 genEquip("gambali","",1,1,"Brache di Tela", "difesa",1,"Almeno coprono le ginocchia",["negozio"]),
 genEquip("gambali","",1,2,"Schinieri di Cuoio","difesa",1,"Proteggono gli stinchi",["negozio","esplorazione"]),
 genEquip("gambali","",1,3,"Calze di Lana", "difesa",1,"Caldo ma non protettivo",["esplorazione"]),
 genEquip("gambali","",2,1,"Gambali di Ferro", "difesa",3,"Pesanti ma efficaci",["negozio"]),
 genEquip("gambali","",2,2,"Schinieri Rinforzati","difesa",4,"Piastre d'acciaio aggiunte",["negozio","loot"]),
 genEquip("gambali","",2,3,"Gambali a Lamelle", "difesa",3,"Protezione mobile",["negozio"]),
 genEquip("gambali","",3,1,"Gambali del Paladino","difesa",6,"Parte di un set benedetto",["negozio","loot"]),
 genEquip("gambali","",3,2,"Schinieri del Gladiatore","difesa",7,"Scene di combattimento decorate",["loot"]),
 genEquip("gambali","",3,3,"Gambali del Crociato","difesa",6,"Resistenti come la fede",["negozio"]),
 genEquip("gambali","",4,1,"Gambali del Campione","difesa",9,"Nessun colpo li ha mai scalfiti",["loot"]),
 genEquip("gambali","",4,2,"Gambali Infuocati", "difesa",10,"Ardono di fuoco eterno",["loot"]),
 genEquip("gambali","",4,3,"Gambali Glaciali", "difesa",9,"Freddi come l'inverno",["loot"]),
 genEquip("gambali","",5,1,"Gambali del Fulmine","difesa",12,"Veloci come il fulmine",["loot"]),
 genEquip("gambali","",5,2,"Gambali Lunari", "difesa",13,"Brillano sotto la luna",["loot"]),
 genEquip("gambali","",5,3,"Gambali del Drago", "difesa",12,"Squame di drago alle gambe",["loot"]),
 genEquip("gambali","",6,1,"Gambali Velenosi", "difesa",15,"Avvelenano i nemici di contatto",["loot"]),
 genEquip("gambali","",6,2,"Gambali di Diamante","difesa",16,"Indistruttibili come il diamante",["loot"]),
 genEquip("gambali","",6,3,"Gambali dell'Ombra","difesa",15,"Invisibili nell'oscurità",["loot"]),
 genEquip("gambali","",7,1,"Gambali Regali", "difesa",19,"Solo per chi ha valore reale",["loot"]),
 genEquip("gambali","",7,2,"Gambali Stellari", "difesa",20,"Caduti dal cielo in fiamme",["loot"]),
 genEquip("gambali","",7,3,"Gambali Arcani", "difesa",19,"Protezione magica assoluta",["loot"]),
 genEquip("gambali","",8,1,"Gambali Meteorici", "difesa",23,"Forgiati da metallo cosmico",["loot"]),
 genEquip("gambali","",8,2,"Gambali del Titano","difesa",24,"Pesanti come un gigante",["loot"]),
 genEquip("gambali","",8,3,"Gambali dell'Oblio","difesa",23,"Annullano qualsiasi impatto",["loot"]),
 genEquip("gambali","",9,1,"Gambali Primordiali","difesa",27,"Antichi quanto il mondo",["loot"]),
 genEquip("gambali","",9,2,"Gambali Eterni", "difesa",29,"Non si sono mai rotti",["loot"]),
 genEquip("gambali","",9,3,"Gambali Cosmici", "difesa",28,"Proteggono fino all'anima",["loot"]),
 genEquip("gambali","",10,1,"Gambali Eterei", "difesa",32,"Fatti di pura luce cristallizzata",["loot"]),
 genEquip("gambali","",10,2,"Gambali dell'Asceso","difesa",34,"Nessun colpo li scalfisce",["loot"]),
 genEquip("gambali","",10,3,"Sandali degli Dei","difesa",33,"Dono divino per i prescelti",["loot"]),

 // ── BRACCIALI (velocità o critico alternati) ──
 genEquip("bracciali","",1,1,"Cinturino di Corda", "velocita",1,"Migliora l'impugnatura",["negozio"]),
 genEquip("bracciali","",1,2,"Bracciale di Cuoio", "critico",1, "Rinforza il polso",["negozio","esplorazione"]),
 genEquip("bracciali","",1,3,"Catena del Prigioniero","velocita",1,"Tolta da un carceriere",["esplorazione"]),
 genEquip("bracciali","",2,1,"Polsini di Ferro", "velocita",2,"Proteggono i polsi",["negozio"]),
 genEquip("bracciali","",2,2,"Amuleto del Guerriero", "critico",2, "Guida la mano nei colpi",["negozio","loot"]),
 genEquip("bracciali","",2,3,"Bracciali a Lamelle", "velocita",3,"Mobili e resistenti",["negozio"]),
 genEquip("bracciali","",3,1,"Guanti del Duellante", "critico",4, "Precisione al duello",["negozio","loot"]),
 genEquip("bracciali","",3,2,"Polsini del Gladiatore","velocita",5,"Portati nell'arena",["loot"]),
 genEquip("bracciali","",3,3,"Bracciali del Templare","critico",4, "Bendetti dall'ordine",["negozio"]),
 genEquip("bracciali","",4,1,"Bracciali del Campione","velocita",6,"Velocità da campione",["loot"]),
 genEquip("bracciali","",4,2,"Polsini Infuocati", "critico",7, "I colpi bruciano",["loot"]),
 genEquip("bracciali","",4,3,"Bracciali Glaciali", "velocita",6,"Movimenti freddi e precisi",["loot"]),
 genEquip("bracciali","",5,1,"Polsini del Fulmine", "velocita",8,"Riflessi soprannaturali",["loot"]),
 genEquip("bracciali","",5,2,"Bracciali Lunari", "critico",9, "Precisi come la luna piena",["loot"]),
 genEquip("bracciali","",5,3,"Artigli del Drago", "velocita",8,"Velocità di un drago",["loot"]),
 genEquip("bracciali","",6,1,"Polsini Velenosi", "critico",10,"Il veleno entra nel colpo",["loot"]),
 genEquip("bracciali","",6,2,"Bracciali di Diamante", "velocita",11,"Indistruttibili",["loot"]),
 genEquip("bracciali","",6,3,"Polsini dell'Ombra", "critico",10,"Colpisce dal nulla",["loot"]),
 genEquip("bracciali","",7,1,"Polsini Regali", "velocita",13,"Autorità nel gesto",["loot"]),
 genEquip("bracciali","",7,2,"Bracciali Stellari", "critico",14,"Precisi come le stelle",["loot"]),
 genEquip("bracciali","",7,3,"Polsini Arcani", "velocita",13,"Magicamente veloci",["loot"]),
 genEquip("bracciali","",8,1,"Polsini Meteorici", "critico",16,"Impatto da meteorite",["loot"]),
 genEquip("bracciali","",8,2,"Bracciali del Titano", "velocita",17,"Forza di un titano",["loot"]),
 genEquip("bracciali","",8,3,"Polsini dell'Oblio", "critico",16,"Colpi dimenticati dai nemici",["loot"]),
 genEquip("bracciali","",9,1,"Polsini Primordiali", "velocita",20,"Antichi quanto il mondo",["loot"]),
 genEquip("bracciali","",9,2,"Bracciali Eterni", "critico",21,"Non si sono mai rotti",["loot"]),
 genEquip("bracciali","",9,3,"Polsini Cosmici", "velocita",20,"Riflessi cosmici",["loot"]),
 genEquip("bracciali","",10,1,"Polsini dell'Asceso", "velocita",24,"Velocità leggendaria",["loot"]),
 genEquip("bracciali","",10,2,"Guanti Divini", "critico",25,"Ogni colpo è perfetto",["loot"]),
 genEquip("bracciali","",10,3,"Polsini Eterei", "velocita",23,"Fatti di pura energia",["loot"]),
];

/* ── Raggruppa equipaggiamento per slot ── */
export const EQUIP_BY_SLOT = {};
for (const e of EQUIPMENT_POOL) {
 if (!EQUIP_BY_SLOT[e.slot]) EQUIP_BY_SLOT[e.slot] = [];
 EQUIP_BY_SLOT[e.slot].push(e);
}

/* ══════════════════════════════════════════════════════════
 RELIQUIE — bonus su statistiche per 24h (vanno in zaino)
══════════════════════════════════════════════════════════ */
export const RELICS = [
 {id:"r01",name:"Artiglio del Lupo", icon:"",stat:"forza", bonus:0.35,desc:"+35% FORZA per 24h"},
 {id:"r02",name:"Occhio del Corvo", icon:"",stat:"velocita", bonus:0.40,desc:"+40% VELOCITÀ per 24h"},
 {id:"r03",name:"Cuore di Pietra", icon:"",stat:"costituzione",bonus:0.50,desc:"+50% PV MAX per 24h"},
 {id:"r04",name:"Lama del Mercenario", icon:"",stat:"forza", bonus:0.25,desc:"+25% FORZA per 24h"},
 {id:"r05",name:"Piuma dell'Arpìa", icon:"",stat:"velocita", bonus:0.30,desc:"+30% VELOCITÀ per 24h"},
 {id:"r06",name:"Scaglia del Drago", icon:"",stat:"costituzione",bonus:0.40,desc:"+40% PV MAX per 24h"},
 {id:"r07",name:"Dente del Vampiro", icon:"",stat:"forza", bonus:0.45,desc:"+45% FORZA per 24h"},
 {id:"r08",name:"Sandalo della Fenice", icon:"",stat:"velocita", bonus:0.50,desc:"+50% VELOCITÀ per 24h"},
 {id:"r09",name:"Osso del Titano", icon:"",stat:"costituzione",bonus:0.60,desc:"+60% PV MAX per 24h"},
 {id:"r10",name:"Frammento dell'Asceso",icon:"",stat:"forza", bonus:0.55,desc:"+55% FORZA per 24h"},
 {id:"r11",name:"Cristallo della Mente",icon:"",stat:"furtivita", bonus:0.40,desc:"+40% FURTIVITÀ per 24h"},
 {id:"r12",name:"Rosa Spinosa", icon:"",stat:"critico", bonus:0.50,desc:"+50% CRITICO per 24h"},
 {id:"r13",name:"Erba della Vita", icon:"",stat:"guarigione", bonus:0.60,desc:"+60% GUARIGIONE per 24h"},
 {id:"r14",name:"Medaglione della Sorte",icon:"",stat:"fortuna", bonus:0.80,desc:"+80% FORTUNA per 24h"},
 {id:"r15",name:"Amuleto della Velocità",icon:"",stat:"velocita", bonus:0.35,desc:"+35% VELOCITÀ per 24h"},
];

/* ══════════════════════════════════════════════════════════
 TREASURES — 100 oggetti con valore in denari, 5 tier
══════════════════════════════════════════════════════════ */
export const TREASURES = [
 // Tier 1 (3-8 den)
 {id:"t001",name:"Borsellino Sgualcito", icon:"",tier:1,minV:3,maxV:6},
 {id:"t002",name:"Monete Sparse", icon:"",tier:1,minV:4,maxV:7},
 {id:"t003",name:"Coltello da Caccia", icon:"",tier:1,minV:5,maxV:8},
 {id:"t004",name:"Scarpe di Cuoio", icon:"",tier:1,minV:3,maxV:6},
 {id:"t005",name:"Fiasca di Vino", icon:"",tier:1,minV:4,maxV:7},
 {id:"t006",name:"Dadi da Gioco", icon:"",tier:1,minV:5,maxV:8},
 {id:"t007",name:"Pietra Levigata", icon:"",tier:1,minV:6,maxV:8},
 {id:"t008",name:"Moneta nel Pane", icon:"",tier:1,minV:3,maxV:5},
 {id:"t009",name:"Ferro di Cavallo", icon:"",tier:1,minV:4,maxV:6},
 {id:"t010",name:"Mappa Incomprensibile", icon:"",tier:1,minV:6,maxV:8},
 {id:"t011",name:"Ciuffo di Erbe", icon:"",tier:1,minV:3,maxV:5},
 {id:"t012",name:"Vecchia Moneta", icon:"",tier:1,minV:4,maxV:6},
 {id:"t013",name:"Anello di Stagno", icon:"",tier:1,minV:5,maxV:7},
 {id:"t014",name:"Osso Scolpito", icon:"",tier:1,minV:3,maxV:6},
 {id:"t015",name:"Sacchetto di Sale", icon:"",tier:1,minV:4,maxV:7},
 {id:"t016",name:"Candela Profumata", icon:"",tier:1,minV:5,maxV:8},
 {id:"t017",name:"Frammento di Ceramica", icon:"",tier:1,minV:3,maxV:5},
 {id:"t018",name:"Piuma Rara", icon:"",tier:1,minV:4,maxV:6},
 {id:"t019",name:"Tappo di Bottiglia", icon:"",tier:1,minV:3,maxV:5},
 {id:"t020",name:"Dente Animale", icon:"",tier:1,minV:4,maxV:7},
 // Tier 2 (9-18 den)
 {id:"t021",name:"Cassa Sfondata", icon:"",tier:2,minV:9,maxV:12},
 {id:"t022",name:"Spada Arrugginita", icon:"",tier:2,minV:11,maxV:14},
 {id:"t023",name:"Calice d'Argento", icon:"",tier:2,minV:13,maxV:16},
 {id:"t024",name:"Sella di Cavallo", icon:"",tier:2,minV:10,maxV:13},
 {id:"t025",name:"Bottino di Predone", icon:"",tier:2,minV:11,maxV:15},
 {id:"t026",name:"Tomo Strappato", icon:"",tier:2,minV:13,maxV:17},
 {id:"t027",name:"Elmo Ammaccato", icon:"",tier:2,minV:11,maxV:14},
 {id:"t028",name:"Gemma Opaca", icon:"",tier:2,minV:12,maxV:16},
 {id:"t029",name:"Bussola Rotta", icon:"",tier:2,minV:8,maxV:12},
 {id:"t030",name:"Fiala di Veleno", icon:"",tier:2,minV:14,maxV:18},
 {id:"t031",name:"Maschera di Legno", icon:"",tier:2,minV:10,maxV:14},
 {id:"t032",name:"Pergamena Strappata", icon:"",tier:2,minV:9,maxV:13},
 {id:"t033",name:"Chiave Arrugginita", icon:"",tier:2,minV:11,maxV:15},
 {id:"t034",name:"Borsa di Sabbia", icon:"",tier:2,minV:10,maxV:14},
 {id:"t035",name:"Specchio Incrinato", icon:"",tier:2,minV:12,maxV:16},
 {id:"t036",name:"Forcella di Osso", icon:"",tier:2,minV:9,maxV:13},
 {id:"t037",name:"Anello con Corniola", icon:"",tier:2,minV:13,maxV:17},
 {id:"t038",name:"Mappa Parziale", icon:"",tier:2,minV:10,maxV:15},
 {id:"t039",name:"Corno di Caccia", icon:"",tier:2,minV:11,maxV:15},
 {id:"t040",name:"Statuetta di Pietra", icon:"",tier:2,minV:12,maxV:16},
 // Tier 3 (19-35 den)
 {id:"t041",name:"Statua Parlante", icon:"",tier:3,minV:20,maxV:28},
 {id:"t042",name:"Scudo con Stemma", icon:"",tier:3,minV:18,maxV:26},
 {id:"t043",name:"Pergamena Sigillata", icon:"",tier:3,minV:22,maxV:30},
 {id:"t044",name:"Anello con Rubino", icon:"",tier:3,minV:24,maxV:32},
 {id:"t045",name:"Cristallo Pulsante", icon:"",tier:3,minV:25,maxV:33},
 {id:"t046",name:"Dente di Drago", icon:"",tier:3,minV:23,maxV:31},
 {id:"t047",name:"Mantello di Seta Nera", icon:"",tier:3,minV:21,maxV:29},
 {id:"t048",name:"Libro dei Morti", icon:"",tier:3,minV:19,maxV:27},
 {id:"t049",name:"Orologio senza Lancette", icon:"⏱",tier:3,minV:22,maxV:30},
 {id:"t050",name:"Forziere Miniatura", icon:"",tier:3,minV:24,maxV:33},
 {id:"t051",name:"Collana di Ambra", icon:"",tier:3,minV:20,maxV:28},
 {id:"t052",name:"Calice di Ossidiana", icon:"",tier:3,minV:23,maxV:31},
 {id:"t053",name:"Maschera d'Oro", icon:"",tier:3,minV:25,maxV:35},
 {id:"t054",name:"Gemma Sanguigna", icon:"",tier:3,minV:22,maxV:30},
 {id:"t055",name:"Tomo Arcano", icon:"",tier:3,minV:21,maxV:29},
 {id:"t056",name:"Astrolabio Rotto", icon:"",tier:3,minV:19,maxV:27},
 {id:"t057",name:"Sigillo d'Argento", icon:"",tier:3,minV:24,maxV:32},
 {id:"t058",name:"Frammento di Reliquia", icon:"",tier:3,minV:23,maxV:31},
 {id:"t059",name:"Fiala di Luce", icon:"",tier:3,minV:25,maxV:34},
 {id:"t060",name:"Pietra Runata", icon:"",tier:3,minV:20,maxV:28},
 // Tier 4 (36-60 den)
 {id:"t061",name:"Corona Spezzata", icon:"",tier:4,minV:38,maxV:52},
 {id:"t062",name:"Armatura dell'Abisso", icon:"",tier:4,minV:40,maxV:54},
 {id:"t063",name:"Mappa Città Proibita", icon:"",tier:4,minV:42,maxV:56},
 {id:"t064",name:"Sfera Incrinata", icon:"",tier:4,minV:36,maxV:50},
 {id:"t065",name:"Libro delle Leggi Arcane", icon:"",tier:4,minV:38,maxV:52},
 {id:"t066",name:"Calice del Re Caduto", icon:"",tier:4,minV:44,maxV:58},
 {id:"t067",name:"Spada della Mezzanotte", icon:"",tier:4,minV:42,maxV:56},
 {id:"t068",name:"Reliquia del Tempio", icon:"",tier:4,minV:36,maxV:50},
 {id:"t069",name:"Diario del Grande Mago", icon:"",tier:4,minV:40,maxV:54},
 {id:"t070",name:"Cuore di Drago", icon:"",tier:4,minV:44,maxV:60},
 {id:"t071",name:"Amuleto dei Re", icon:"",tier:4,minV:38,maxV:52},
 {id:"t072",name:"Pietra Filosofale Falsa", icon:"",tier:4,minV:40,maxV:54},
 {id:"t073",name:"Trofeo del Campione", icon:"",tier:4,minV:42,maxV:56},
 {id:"t074",name:"Mappa del Tesoro Reale", icon:"",tier:4,minV:44,maxV:58},
 {id:"t075",name:"Occhio di Cristallo", icon:"",tier:4,minV:38,maxV:52},
 {id:"t076",name:"Diadema d'Oro", icon:"",tier:4,minV:40,maxV:54},
 {id:"t077",name:"Tomo del Negromanzia", icon:"",tier:4,minV:36,maxV:50},
 {id:"t078",name:"Collana del Drago Antico", icon:"",tier:4,minV:42,maxV:56},
 {id:"t079",name:"Sigillo Imperiale", icon:"",tier:4,minV:44,maxV:58},
 {id:"t080",name:"Frammento di Meteora", icon:"",tier:4,minV:40,maxV:55},
 // Tier 5 (61-100 den)
 {id:"t081",name:"Frammento della Luna", icon:"",tier:5,minV:62,maxV:78},
 {id:"t082",name:"Occhio del Leviatano", icon:"",tier:5,minV:70,maxV:86},
 {id:"t083",name:"Prima Pagina del Tempo", icon:"",tier:5,minV:78,maxV:94},
 {id:"t084",name:"Sangue di Titano", icon:"",tier:5,minV:68,maxV:84},
 {id:"t085",name:"Chiave senza Serratura", icon:"",tier:5,minV:60,maxV:76},
 {id:"t086",name:"Mantello dell'Asceso", icon:"",tier:5,minV:76,maxV:92},
 {id:"t087",name:"Stella Caduta", icon:"",tier:5,minV:64,maxV:80},
 {id:"t088",name:"Sigillo dell'Oblio", icon:"",tier:5,minV:72,maxV:88},
 {id:"t089",name:"Corona dei Mille Anni", icon:"",tier:5,minV:80,maxV:96},
 {id:"t090",name:"La Pietra dell'Origine", icon:"",tier:5,minV:84,maxV:100},
 {id:"t091",name:"Lacrime di Drago", icon:"",tier:5,minV:66,maxV:82},
 {id:"t092",name:"Sinfonia delle Stelle", icon:"",tier:5,minV:70,maxV:86},
 {id:"t093",name:"Frammento del Sole", icon:"",tier:5,minV:74,maxV:90},
 {id:"t094",name:"Vuoto Primordiale", icon:"",tier:5,minV:78,maxV:94},
 {id:"t095",name:"Libro dell'Eternità", icon:"",tier:5,minV:82,maxV:98},
 {id:"t096",name:"Scheggia del Velo", icon:"",tier:5,minV:68,maxV:84},
 {id:"t097",name:"Cuore di Stelle", icon:"",tier:5,minV:72,maxV:88},
 {id:"t098",name:"Essenza Primordiale", icon:"",tier:5,minV:76,maxV:92},
 {id:"t099",name:"Respiro del Cosmo", icon:"",tier:5,minV:80,maxV:96},
 {id:"t100",name:"Il Tutto e il Nulla", icon:"",tier:5,minV:86,maxV:100},
];

/* ══════════════════════════════════════════════════════════
 POZIONI
══════════════════════════════════════════════════════════ */
export const POTIONS = [
 {id:"pot01",name:"Pozione Curativa Piccola",icon:"",prezzo:8, desc:"Ripristina 30 PV istantaneamente", effect:{tipo:"heal",val:30}},
 {id:"pot02",name:"Pozione Curativa Media", icon:"",prezzo:18, desc:"Ripristina 70 PV istantaneamente", effect:{tipo:"heal",val:70}},
 {id:"pot03",name:"Pozione Curativa Grande", icon:"",prezzo:30, desc:"Ripristina 100 PV istantaneamente", effect:{tipo:"heal",val:100}},
 {id:"pot04",name:"Pozione Revitalizzante", icon:"",prezzo:90, desc:"Ripristina 300 PV istantaneamente", effect:{tipo:"heal",val:300}},
 {id:"pot05",name:"Pozione Rigenerante", icon:"",prezzo:22, desc:"Raddoppia regen PV per 24 ore", effect:{tipo:"regen_boost",durata:86400000}},
 {id:"pot06",name:"Pozione dei Punti Azione Piccola",icon:"",prezzo:25, desc:"Ripristina 3 Punti Azione", effect:{tipo:"restore_pa",val:3}},
 {id:"pot07",name:"Pozione dei Punti Azione Media",icon:"",prezzo:70, desc:"Ripristina 10 Punti Azione", effect:{tipo:"restore_pa",val:10}},
];

/* ══════════════════════════════════════════════════════════
 BESTIARIO — 150 nemici (livello 1-150)
 Ogni nemico ha img: "img/enemies/<id>.png"
 Es: e001 → img/enemies/e001.png
══════════════════════════════════════════════════════════ */
function npc(id, lvl, name, icon, human, forza, velocita, destrezza, critico, costituzione, trait, tags) {
 return {
 id, lvl, name, icon,
 human: !!human,
 forza, velocita, destrezza, critico, costituzione,
 trait, tags: tags || [],
 img: `img/enemies/${id}.png`,
 };
}

export const BESTIARY = [
 npc("e001",1,"Ratto Gigante","",0,8,6,4,2,45,"Attacca in gruppo",["bestia"]),
 npc("e002",2,"Pipistrello Notturno","",0,10,10,6,3,55,"Volo rapido",["bestia"]),
 npc("e003",3,"Lucertola Velenosa","",0,13,8,5,4,65,"Veleno di contatto",["bestia"]),
 npc("e004",4,"Cane Randagio","",0,16,12,7,4,80,"Schiva spesso",["bestia"]),
 npc("e005",5,"Goblin Debole","",1,18,11,6,5,90,"Colpo sorpresa",["goblin"]),
 npc("e006",6,"Serpente Nano","",0,20,14,9,5,100,"Morde e fugge",["bestia"]),
 npc("e007",7,"Fungo Ambulante","",0,22,7,4,3,120,"Carica finale",["bestia"]),
 npc("e008",8,"Corvo Mutante","",0,24,16,10,6,110,"Colpo sorpresa",["bestia"]),
 npc("e009",9,"Rana Gigante","",0,26,9,6,4,140,"Corazza naturale",["bestia"]),
 npc("e010",10,"Goblin Guerriero","",1,30,13,8,7,150,"Attacca rapidamente",["goblin"]),
 npc("e011",11,"Bandito Scalcinato","",1,32,15,9,7,160,"Amboscatore",["bandito","umano"]),
 npc("e012",12,"Lupo Grigio","",0,35,18,12,8,170,"Morso preciso",["lupo"]),
 npc("e013",13,"Scheletro Antico","",0,37,12,5,9,155,"Non sente dolore",["nonmorto","scheletro","umano"]),
 npc("e014",14,"Ragno Gigante","",0,39,17,13,10,180,"Tesse trappole",["ragno","bestia"]),
 npc("e015",15,"Contadino Folle","",1,42,14,10,9,200,"Furia cieca",["umano"]),
 npc("e016",16,"Gnomo Armato","",1,44,20,14,10,190,"Alta iniziativa",["umano"]),
 npc("e017",17,"Coccodrillo Giovane","",0,47,11,8,8,230,"Pelle coriacea",["bestia"]),
 npc("e018",18,"Cinghiale Selvatico","",0,50,15,10,9,250,"Carica devastante",["bestia"]),
 npc("e019",19,"Recluta Rinnegata","",1,53,17,12,11,220,"Colpo brutale",["bandito","umano"]),
 npc("e020",20,"Goblin Sciamano","",1,55,19,14,13,210,"Magia oscura",["goblin","umano"]),
 npc("e021",21,"Lupo Alpha","",0,58,22,15,12,270,"Carica devastante",["lupo","bestia"]),
 npc("e022",22,"Bandito Capitano","",1,61,18,13,13,260,"Colpo preciso",["bandito","umano"]),
 npc("e023",23,"Ghoul","",0,64,14,10,12,290,"Artigli infetti",["nonmorto"]),
 npc("e024",24,"Troll Giovane","",0,67,13,9,11,320,"Rigenerazione lenta",["troll"]),
 npc("e025",25,"Orso della Foresta","",0,70,16,11,13,340,"Abbraccio letale",["bestia"]),
 npc("e026",26,"Cultista Oscuro","",1,73,20,15,15,300,"Rituale di danno",["umano"]),
 npc("e027",27,"Spirito Errante","",0,76,24,18,14,280,"Incorporeo",["spirito","nonmorto"]),
 npc("e028",28,"Ogre Minore","",0,79,12,8,12,380,"Forza colossale",["ogre"]),
 npc("e029",29,"Scheletro Guerriero","",0,82,16,10,16,330,"Ossatura rinforzata",["nonmorto","scheletro","umano"]),
 npc("e030",30,"Licantropo","",0,85,21,16,17,360,"Trasformazione lunare",["lupo","bestia"]),
 npc("e031",31,"Golem di Fango","",0,88,9,5,13,420,"Quasi immobile",["golem"]),
 npc("e032",32,"Vampiro Minore","",0,91,23,17,18,380,"Drena vita",["vampiro","nonmorto","umano"]),
 npc("e033",33,"Elementale d'Acqua","",0,94,19,15,16,400,"Flusso inarrestabile",["elementale"]),
 npc("e034",34,"Mercenario Rinnegato","",1,97,22,16,19,410,"Combattente esperto",["bandito","umano"]),
 npc("e035",35,"Troll del Fiume","",0,100,15,11,15,450,"Rigenerazione in acqua",["troll"]),
 npc("e036",36,"Orso Polare","",0,104,17,12,16,480,"Colpo devastante",["bestia"]),
 npc("e037",37,"Sirena","",0,107,27,20,18,420,"Canto ammaliante",["bestia"]),
 npc("e038",38,"Amazzone Giovane","",1,110,23,17,20,440,"Nessuna debolezza",["bandito","umano"]),
 npc("e039",39,"Ghoul Anziano","",0,113,17,12,19,500,"Ferocia aumentata",["nonmorto"]),
 npc("e040",40,"Golem di Pietra","",0,117,10,6,15,560,"Corazza adamantina",["golem"]),
 npc("e041",41,"Spettro Guerriero","",0,120,28,21,20,480,"Colpi spettrali",["spirito","nonmorto"]),
 npc("e042",42,"Idra Minore","",0,123,14,10,18,600,"Teste rigeneranti",["drago","bestia"]),
 npc("e043",43,"Elementale del Fuoco","",0,127,22,16,22,540,"Brucia tutto",["elementale"]),
 npc("e044",44,"Lich Apprendista","",1,130,25,19,24,510,"Magia della morte",["nonmorto"]),
 npc("e045",45,"Cavaliere Non-Morto","",1,134,20,14,22,580,"Armatura ossea",["nonmorto","umano"]),
 npc("e046",46,"Mannaro Anziano","",0,137,24,18,23,560,"Furia bestiale",["lupo","bestia"]),
 npc("e047",47,"Basilisco","",0,141,18,13,21,640,"Sguardo pietrificante",["bestia"]),
 npc("e048",48,"Strega della Palude","",1,144,27,20,26,590,"Maledizione",["umano"]),
 npc("e049",49,"Minotauro","",0,148,21,15,24,680,"Carica del labirinto",["bestia"]),
 npc("e050",50,"Arpia","",0,152,29,22,27,620,"Ipnosi letale",["bestia"]),
 npc("e051",51,"Demone Minore","",0,156,26,19,25,650,"Fuoco infernale",["demone"]),
 npc("e052",52,"Golem di Ossidiana","",0,160,12,7,20,740,"Indistruttibile",["golem"]),
 npc("e053",53,"Troll Antico","",0,164,17,12,22,780,"Rigenerazione totale",["troll"]),
 npc("e054",54,"Spirito del Guerriero","",0,168,31,24,28,700,"Possessione",["spirito","nonmorto"]),
 npc("e055",55,"Elementale della Terra","",0,173,13,9,21,860,"Forza tellurica",["elementale"]),
 npc("e056",56,"Licantropo Alfa","",0,177,27,20,29,780,"Ululato di guerra",["lupo","bestia"]),
 npc("e057",57,"Necromante Rosso","",1,181,30,23,32,740,"Esercito di morti",["umano"]),
 npc("e058",58,"Vampiro Antico","",0,186,33,25,30,800,"Nebbia oscura",["vampiro","nonmorto","umano"]),
 npc("e059",59,"Gigante delle Tempeste","",0,190,23,17,28,920,"Fulmine divino",["bestia"]),
 npc("e060",60,"Medusa","",0,195,26,19,33,850,"Sguardo letale",["bestia"]),
 npc("e061",61,"Fenice Corrotta","",0,199,34,26,31,880,"Rinascita oscura",["bestia"]),
 npc("e062",62,"Kraken Minore","",0,204,20,15,30,980,"Tentacoli devastanti",["bestia"]),
 npc("e063",63,"Cavaliere del Caos","",1,209,28,21,35,900,"Aura di caos",["umano","demone"]),
 npc("e064",64,"Diavolo Minore","",0,214,32,24,34,940,"Corruzione infernale",["demone"]),
 npc("e065",65,"Drago Giovane","",0,219,30,22,36,1050,"Fuoco primordiale",["drago"]),
 npc("e066",66,"Lich","",1,224,35,27,38,980,"Filatterio eterno",["nonmorto"]),
 npc("e067",67,"Elementale del Vento","",0,229,40,32,35,900,"Turbine incessante",["elementale"]),
 npc("e068",68,"Golem di Lava","",0,235,16,11,30,1120,"Lava incandescente",["golem","elementale"]),
 npc("e069",69,"Valchiria","",0,240,34,26,37,1060,"Frenesia demoniaca",["demone","umano"]),
 npc("e070",70,"Conte Vampiro","",0,246,36,28,39,1080,"Aura vampirica",["vampiro","nonmorto","umano"]),
 npc("e071",71,"Idra a Cinque Teste","",0,252,22,16,38,1200,"Rigenerazione rapida",["drago","bestia"]),
 npc("e072",72,"Signore dei Lupi","",0,258,30,23,40,1100,"Branco infinito",["lupo","bestia"]),
 npc("e073",73,"Angelo Corrotto","",0,264,38,29,42,1050,"Grazia profanata",["demone"]),
 npc("e074",74,"Troll di Pietra","",0,270,18,13,34,1340,"Pelle rocciosa",["troll","golem"]),
 npc("e075",75,"Spettro del Re","",0,276,40,31,43,1150,"Terrore regale",["spirito","nonmorto"]),
 npc("e076",76,"Drago di Ghiaccio","",0,283,28,21,41,1250,"Soffio gelido",["drago"]),
 npc("e077",77,"Arcidemone","",0,290,36,28,44,1200,"Potere infernale",["demone"]),
 npc("e078",78,"Leviatano Minore","",0,297,25,19,40,1450,"Dimensioni enormi",["bestia"]),
 npc("e079",79,"Elementale Primordiale","",0,304,38,30,45,1300,"Ogni elemento",["elementale"]),
 npc("e080",80,"Vampiro Leggendario","",0,311,42,33,46,1350,"Legione di servi",["vampiro","nonmorto"]),
 npc("e081",81,"Principe Non-Morto","",1,319,32,25,44,1450,"Esercito dei morti",["nonmorto","scheletro","umano"]),
 npc("e082",82,"Titano Minore","",0,327,22,16,40,1600,"Terremoto con ogni passo",["bestia"]),
 npc("e083",83,"Drago del Tuono","",0,335,35,27,48,1500,"Fulmini dragonici",["drago"]),
 npc("e084",84,"Arcistrega dell'Oblio","",1,343,38,30,50,1420,"Cancella la memoria",["umano"]),
 npc("e085",85,"Guardiano Eterno","",0,352,20,15,44,1800,"Non si stanca mai",["golem"]),
 npc("e086",86,"Signore dei Demoni","",0,361,40,32,52,1550,"Contratto infernale",["demone"]),
 npc("e087",87,"Fenice Nera","",0,370,44,35,50,1480,"Rinascita infinita",["bestia"]),
 npc("e088",88,"Leviatano","",0,379,28,21,47,1750,"Terrore degli abissi",["bestia"]),
 npc("e089",89,"Drago di Cenere","",0,389,38,30,54,1700,"Fuoco primordiale",["drago"]),
 npc("e090",90,"Golem di Diamante","",0,399,14,10,45,2000,"Indistruttibile",["golem"]),
 npc("e091",91,"Troll Leggendario","",0,409,22,16,48,1900,"Immortalità relativa",["troll"]),
 npc("e092",92,"Lich Antico","",1,420,42,34,56,1800,"Poteri cosmici",["nonmorto"]),
 npc("e093",93,"Vampiro del Deserto","",0,431,46,36,57,1850,"Eternità oscura",["vampiro","nonmorto"]),
 npc("e094",94,"Demone dell'Abisso","",0,442,44,35,58,1900,"Abisso senza fondo",["demone"]),
 npc("e095",95,"Lupo Sidereo","",0,453,48,38,55,1800,"Caccia cosmica",["lupo","bestia"]),
 npc("e096",96,"Elementale del Vuoto","",0,465,45,36,59,1950,"Il nulla assoluto",["elementale"]),
 npc("e097",97,"Spettro Primordiale","",0,477,50,40,60,1900,"Incubo vivente",["spirito","nonmorto"]),
 npc("e098",98,"Drago a Tre Teste","",0,490,40,32,62,2100,"Fuoco eterno",["drago"]),
 npc("e099",99,"Angelo Caduto","",0,503,48,38,61,2000,"Redenzione impossibile",["demone"]),
 npc("e100",100,"Titano della Terra","",0,516,25,19,55,2300,"Solidità assoluta",["bestia"]),
 npc("e101",101,"Divoratore di Draghi","",0,530,42,34,63,2200,"Fagocita tutto",["demone"]),
 npc("e102",102,"Drago Nero","",0,544,44,35,65,2250,"Velo di tenebra",["drago"]),
 npc("e103",103,"Re Lich","",1,558,46,37,67,2200,"Solo gli eroi sopravvivono",["nonmorto"]),
 npc("e104",104,"Regina dell'Ira","",0,573,48,38,66,2300,"Frenesia immortale",["demone"]),
 npc("e105",105,"Leviatano Antico","",0,588,30,23,60,2600,"Il mare si oscura",["bestia"]),
 npc("e106",106,"Vampiro dell'Eternità","",0,604,52,41,68,2400,"Immortalità oscura",["vampiro","nonmorto"]),
 npc("e107",107,"Elementale Cosmico","",0,620,50,40,69,2500,"Tutti gli elementi",["elementale"]),
 npc("e108",108,"Guardiano del Velo","",0,636,28,22,63,2800,"Difende la soglia",["golem"]),
 npc("e109",109,"Demone Primordiale","",0,653,54,43,71,2600,"Corruzione assoluta",["demone"]),
 npc("e110",110,"Titano del Fuoco","",0,670,32,25,65,3000,"Fusione con il fuoco",["bestia","elementale"]),
 npc("e111",111,"Idra dell'Abisso","",0,688,26,20,66,3100,"Sette teste immortali",["drago","bestia"]),
 npc("e112",112,"Lich Primordiale","",1,706,50,40,73,2900,"Conoscenza proibita",["nonmorto"]),
 npc("e113",113,"Evocatore Infernale","",0,724,56,45,74,3000,"Dominio infernale",["demone"]),
 npc("e114",114,"Dea della Luna Nera","",0,743,54,43,72,2900,"Oscurità lunare",["lupo","bestia"]),
 npc("e115",115,"Spettro dell'Eternità","",0,762,58,46,75,2950,"Terrore eterno",["spirito","nonmorto"]),
 npc("e116",116,"Drago delle Profondità","",0,782,46,37,77,3300,"Oscurità marina",["drago"]),
 npc("e117",117,"Senza Nome","",0,802,55,44,76,3200,"Oltre la comprensione",["bestia"]),
 npc("e118",118,"Guardiano Primordiale","",0,823,22,17,68,3600,"Nulla lo ferma",["golem"]),
 npc("e119",119,"Angelo Corrotto Antico","",0,844,60,48,78,3250,"Caduta dal paradiso",["demone"]),
 npc("e120",120,"Vampiro Primordiale","",0,866,62,50,79,3300,"Padrone delle tenebre",["vampiro","nonmorto"]),
 npc("e121",121,"Incubo degli Oceani","",0,888,35,27,72,3800,"Imbattibile per i deboli",["bestia"]),
 npc("e122",122,"Signora dei Demoni","",0,910,58,46,80,3500,"Potere assoluto",["demone"]),
 npc("e123",123,"Drago Cosmico","",0,933,50,40,82,3700,"Fuoco cosmico",["drago"]),
 npc("e124",124,"Titano Primordiale","",0,957,28,22,74,4100,"Forza cosmica assoluta",["bestia"]),
 npc("e125",125,"L'Asceso Corrotto","",0,981,64,52,83,3800,"L'apice del potere",["demone"]),
 npc("e126",126,"Elementale del Cosmo","",0,1006,62,50,81,4000,"Tutto e nulla",["elementale"]),
 npc("e127",127,"Lich del Cosmo","",1,1032,56,45,85,3900,"Conoscenza dell'universo",["nonmorto"]),
 npc("e128",128,"Divoratore di Mondi","",0,1058,60,48,84,4200,"Fagocita mondi",["demone"]),
 npc("e129",129,"Drago Primordiale","",0,1085,54,43,87,4400,"Oltre ogni comprensione",["drago"]),
 npc("e130",130,"Giudice delle Anime","",1,1113,58,46,88,4300,"Solo gli eroi leggendari sopravvivono",["nonmorto"]),
 npc("e131",131,"Arcidemon Cosmico","",0,1142,66,53,89,4500,"Cosmo infernale",["demone"]),
 npc("e132",132,"Signore degli Spiriti","",0,1172,68,55,90,4400,"Dominio spettrale",["spirito","nonmorto"]),
 npc("e133",133,"Morte Incarnata","",0,1203,62,50,91,4600,"Morte inevitabile",["nonmorto"]),
 npc("e134",134,"Titano Cosmico","",0,1235,34,27,80,5000,"Forza cosmica",["bestia"]),
 npc("e135",135,"Angelo del Vuoto","",0,1268,70,57,92,4700,"Vuoto angelico",["demone"]),
 npc("e136",136,"Leviatano Primordiale","",0,1302,40,32,83,5400,"Oscurità oceanica",["bestia"]),
 npc("e137",137,"Drago dell'Apocalisse","",0,1337,58,46,94,5200,"Apocalisse dragonica",["drago"]),
 npc("e138",138,"Entità Senza Forma","",0,1374,72,58,93,5100,"Incomprensibile",["demone"]),
 npc("e139",139,"Re dell'Oblio","",1,1412,65,52,95,5400,"Cancella l'esistenza",["nonmorto","demone"]),
 npc("e140",140,"Signore del Caos","",0,1451,68,55,96,5500,"Caos puro",["demone"]),
 npc("e141",141,"Divoratore di Dei","",0,1492,72,58,95,5700,"Mangia le divinità",["demone"]),
 npc("e142",142,"Eterno Non-Morto","",0,1534,62,50,97,5800,"Immortalità vera",["nonmorto"]),
 npc("e143",143,"Drago Eterno","",0,1578,65,52,98,6000,"Fuoco eterno",["drago"]),
 npc("e144",144,"Titano dell'Oblio","",0,1623,38,30,90,6500,"Nulla lo ferma",["bestia"]),
 npc("e145",145,"Angelo Primordiale","",0,1670,75,60,99,6200,"Potere primordiale",["demone"]),
 npc("e146",146,"Leviatano Eterno","",0,1719,45,36,92,7000,"Dimensioni cosmiche",["bestia"]),
 npc("e147",147,"Golem del Creatore","",0,1770,25,20,86,7500,"Fatto dal Creatore",["golem"]),
 npc("e148",148,"Signore del Vuoto","",0,1823,78,63,100,7200,"Il vuoto incarnato",["demone","elementale"]),
 npc("e149",149,"Dea della Morte","",1,1878,70,57,100,7400,"Solo l'Asceso può vincere",["nonmorto","demone"]),
 npc("e150",150,"Creatore del Tempo","",0,1935,72,58,100,7600,"Oltre ogni comprensione",["drago"]),
];

/* ══════════════════════════════════════════════════════════
 WORLD_AREAS — 7 zone del Mondo Esterno
 Sbloccate sequenzialmente completando 20 missioni per area
 (Empireo: 21 missioni speciali)
══════════════════════════════════════════════════════════ */
export const WORLD_AREAS = [
  {
    id: "foresta",
    name: "Foresta Crepuscolare",
    icon: "",
    costoOro: 10,
    costoPA: 5,
    lvlMin: 1, lvlMax: 30,
    missioniRichieste: 20,
    sblocca: "miniere",
    desc: "Boschi oscuri abitati da spiriti e banditi",
  },
  {
    id: "miniere",
    name: "Miniere Sepolte",
    icon: "",
    costoOro: 20,
    costoPA: 6,
    lvlMin: 31, lvlMax: 60,
    missioniRichieste: 20,
    sblocca: "isole",
    desc: "Gallerie profonde, piene di nani rinnegati ed elementali",
  },
  {
    id: "isole",
    name: "Isole dei Naufraghi",
    icon: "",
    costoOro: 35,
    costoPA: 7,
    lvlMin: 61, lvlMax: 90,
    missioniRichieste: 20,
    sblocca: "montagne",
    desc: "Arcipelago maledetto tra pirati spettrali e tritoni",
  },
  {
    id: "montagne",
    name: "Montagne Silenti",
    icon: "",
    costoOro: 55,
    costoPA: 8,
    lvlMin: 91, lvlMax: 120,
    missioniRichieste: 20,
    sblocca: "deserto",
    desc: "Vette eterne dove regnano giganti e draghi",
  },
  {
    id: "deserto",
    name: "Deserto delle Ossa",
    icon: "",
    costoOro: 80,
    costoPA: 9,
    lvlMin: 121, lvlMax: 150,
    missioniRichieste: 20,
    sblocca: "oltretomba",
    desc: "Sabbie infinite di faraoni non-morti e djinn",
  },
  {
    id: "oltretomba",
    name: "Oltretomba",
    icon: "",
    costoOro: 120,
    costoPA: 10,
    lvlMin: 151, lvlMax: 180,
    missioniRichieste: 20,
    sblocca: "empireo",
    desc: "Il regno dei morti — demoni e non-morti dominano",
  },
  {
    id: "empireo",
    name: "Empireo",
    icon: "",
    costoOro: 200,
    costoPA: 12,
    lvlMin: 181, lvlMax: 190,
    missioniRichieste: 21,
    sblocca: null,
    desc: "La dimora degli dei — ogni divinità può essere sconfitta una sola volta",
  },
];

/* ── Nemici per area (estratti dal BESTIARY per livello) ── */
export function getEnemiesForArea(areaId) {
  const area = WORLD_AREAS.find(a => a.id === areaId);
  if (!area) return BESTIARY;
  // Empireo: divinità speciali (e181-e190) — fuori dal BESTIARY normale
  if (areaId === "empireo") return EMPIREO_GODS;
  return BESTIARY.filter(e => e.lvl >= area.lvlMin && e.lvl <= area.lvlMax);
}

/* ── Divinità dell'Empireo (10 nemici unici, non rispawnano) ── */
function god(id, lvl, name, hp, atk, mag, def, trait) {
  return {
    id, lvl, name, icon: "",
    human: false,
    forza: atk, velocita: Math.floor(atk * 0.75), destrezza: def,
    critico: Math.floor(mag * 0.4), costituzione: hp,
    trait, tags: ["divinita"],
    img: `img/enemies/${id}.png`,
    isGod: true,
  };
}
export const EMPIREO_GODS = [
  god("e181", 181, "Valeska",  580, 120, 140, 72, "Dea dell'amore — il suo tocco è veleno e desiderio"),
  god("e182", 182, "Thalmos",  560, 105, 160, 70, "Dio della conoscenza — conosce ogni tua debolezza"),
  god("e183", 183, "Sylvaris", 570, 135, 120, 74, "Dea della caccia — non sbaglia mai un colpo"),
  god("e184", 184, "Ignaroth", 595, 145, 130, 76, "Dio del fuoco — il suo corpo brucia chi si avvicina"),
  god("e185", 185, "Abyssor",  610, 140, 125, 78, "Dio del mare — porta con sé la pressione degli abissi"),
  god("e186", 186, "Lunarys",  575, 115, 155, 73, "Dea della luna — i suoi incantesimi crescono di notte"),
  god("e187", 187, "Solarius", 590, 130, 145, 75, "Dio del sole — la sua luce acceca e brucia"),
  god("e188", 188, "Varos",    620, 160, 100, 80, "Dio della guerra — ogni colpo è letale"),
  god("e189", 189, "Morvath",  600, 125, 165, 78, "Dea della morte — chi cade non risorge"),
  god("e190", 190, "Kaelos",   650, 150, 170, 85, "Dio del tempo — può annullare le tue azioni"),
];

/* ── Bottini divini dell'Empireo ── */
export const EMPIREO_LOOT = [
  { id:"gl01", godId:"e181", name:"Lacrime di Valeska",              value:12000, desc:"Cristalli d'amore cristallizzato" },
  { id:"gl02", godId:"e182", name:"Frammento della Mente di Thalmos",value:13000, desc:"Un pensiero del dio — conoscenza di un'era" },
  { id:"gl03", godId:"e183", name:"Freccia di Sylvaris",             value:12500, desc:"Non manca mai il bersaglio" },
  { id:"gl04", godId:"e184", name:"Cenere di Ignaroth",              value:13500, desc:"Fuoco divino in polvere" },
  { id:"gl05", godId:"e185", name:"Goccia dell'Abisso",              value:14000, desc:"Acqua degli oceani più profondi" },
  { id:"gl06", godId:"e186", name:"Scheggia di Luna",                value:12000, desc:"Frammento della luna stessa" },
  { id:"gl07", godId:"e187", name:"Raggio Solidificato",             value:13000, desc:"Luce del sole condensata in cristallo" },
  { id:"gl08", godId:"e188", name:"Lama Spezzata di Varos",          value:15000, desc:"Metà della spada del dio della guerra" },
  { id:"gl09", godId:"e189", name:"Velo di Morvath",                 value:14500, desc:"Tessuto dell'aldilà" },
  { id:"gl10", godId:"e190", name:"Clessidra di Kaelos",             value:20000, desc:"Ferma il tempo per un istante" },
];

/* ══════════════════════════════════════════════════════════
 AREA_QUESTS — Missioni permanenti per area (non settimanali)
 Completare tutte le missioni di un'area sblocca la successiva
══════════════════════════════════════════════════════════ */
export const AREA_QUESTS = {

  foresta: [
    {id:"f01", n:1,  title:"Primo Passo nel Buio",   type:"spedizioni",   target:1,   desc:"Esegui la tua prima spedizione nella Foresta Crepuscolare"},
    {id:"f02", n:2,  title:"Caccia al Branco",        type:"kills_name",   target:5,   enemy:"Lupo Grigio",          desc:"Uccidi 5 Lupi Grigi"},
    {id:"f03", n:3,  title:"Pulizia dei Sentieri",    type:"kills_name",   target:5,   enemy:"Goblin Frugatore",     desc:"Uccidi 5 Goblin Frugatori"},
    {id:"f04", n:4,  title:"Erborista Improvvisato",  type:"loot_area",    target:3,   desc:"Ottieni 3 oggetti dalla Foresta"},
    {id:"f05", n:5,  title:"Il Bosco Chiama",         type:"spedizioni",   target:3,   desc:"Esegui 3 spedizioni nella Foresta Crepuscolare"},
    {id:"f06", n:6,  title:"Abbattere il Troll",      type:"kills_name",   target:3,   enemy:"Troll Piccolo",        desc:"Uccidi 3 Troll Piccoli"},
    {id:"f07", n:7,  title:"Ragni e Veleni",          type:"kills_name",   target:5,   enemy:"Ragno Cacciatore",     desc:"Uccidi 5 Ragni Cacciatori"},
    {id:"f08", n:8,  title:"Primo Bottino",           type:"denari_area",  target:100, desc:"Accumula 100 denari da bottini della Foresta"},
    {id:"f09", n:9,  title:"La Strega del Bosco",     type:"kills_name",   target:2,   enemy:"Strega del Bosco",     desc:"Uccidi 2 Streghe del Bosco"},
    {id:"f10", n:10, title:"Sopravvissuto",           type:"spedizioni",   target:5,   desc:"Esegui 5 spedizioni nella Foresta"},
    {id:"f11", n:11, title:"Cacciatore di Spiriti",   type:"kills_area",   target:4,   area:"foresta",               desc:"Sconfiggi 4 Spiriti nella Foresta"},
    {id:"f12", n:12, title:"Borsa Piena",             type:"loot_area",    target:5,   desc:"Ottieni 5 oggetti dalla Foresta"},
    {id:"f13", n:13, title:"L'Orso Notturno",         type:"kills_name",   target:1,   enemy:"Orso Notturno",        desc:"Uccidi l'Orso Notturno"},
    {id:"f14", n:14, title:"Esploratore del Bosco",   type:"spedizioni",   target:10,  desc:"Esegui 10 spedizioni nella Foresta"},
    {id:"f15", n:15, title:"Il Branco è Spezzato",    type:"kills_name",   target:1,   enemy:"Mannaro Alfa",         desc:"Uccidi il Mannaro Alfa"},
    {id:"f16", n:16, title:"Ricchezze del Bosco",     type:"denari_area",  target:500, desc:"Accumula 500 denari da bottini della Foresta"},
    {id:"f17", n:17, title:"Abbattere il Centauro",   type:"kills_name",   target:2,   enemy:"Centauro Selvaggio",   desc:"Uccidi 2 Centauri Selvaggi"},
    {id:"f18", n:18, title:"La Caccia Selvaggia",     type:"kills_name",   target:1,   enemy:"Caccia Selvaggia",     desc:"Sconfiggi la Caccia Selvaggia"},
    {id:"f19", n:19, title:"Veterano del Bosco",      type:"spedizioni",   target:15,  desc:"Esegui 15 spedizioni nella Foresta"},
    {id:"f20", n:20, title:"La Regina Cade",          type:"kills_name",   target:1,   enemy:"Regina delle Streghe", desc:"Sconfiggi la Regina delle Streghe", sblocca:"miniere"},
  ],

  miniere: [
    {id:"m01", n:1,  title:"Discesa nelle Tenebre",    type:"spedizioni",  target:1,   desc:"Prima spedizione nelle Miniere Sepolte"},
    {id:"m02", n:2,  title:"Infestazione di Ratti",    type:"kills_name",  target:5,   enemy:"Ratto delle Miniere",   desc:"Uccidi 5 Ratti delle Miniere"},
    {id:"m03", n:3,  title:"Coboldi nel Tunnel",       type:"kills_name",  target:5,   enemy:"Coboldo Trappatore",    desc:"Uccidi 5 Coboldi Trappatori"},
    {id:"m04", n:4,  title:"Raccolta di Minerali",     type:"loot_area",   target:3,   desc:"Ottieni 3 oggetti dalle Miniere"},
    {id:"m05", n:5,  title:"I Tunnel Chiamano",        type:"spedizioni",  target:3,   desc:"Esegui 3 spedizioni nelle Miniere"},
    {id:"m06", n:6,  title:"Pace ai Caduti",           type:"kills_name",  target:4,   enemy:"Minatore Morto",        desc:"Sconfiggi 4 Minatori Morti"},
    {id:"m07", n:7,  title:"Fermare il Verme",         type:"kills_name",  target:3,   enemy:"Verme Perforatore",     desc:"Uccidi 3 Vermi Perforatori"},
    {id:"m08", n:8,  title:"Oro delle Profondità",     type:"denari_area", target:300, desc:"Accumula 300 denari da bottini delle Miniere"},
    {id:"m09", n:9,  title:"Il Golem di Carbone",      type:"kills_name",  target:2,   enemy:"Golem di Carbone",      desc:"Sconfiggi 2 Golem di Carbone"},
    {id:"m10", n:10, title:"Minatore Temerario",       type:"spedizioni",  target:5,   desc:"Esegui 5 spedizioni nelle Miniere"},
    {id:"m11", n:11, title:"Caccia all'Elementale",    type:"kills_name",  target:3,   enemy:"Elementale di Pietra",  desc:"Sconfiggi 3 Elementali nelle Miniere"},
    {id:"m12", n:12, title:"Vena Preziosa",            type:"loot_area",   target:5,   desc:"Ottieni 5 oggetti dalle Miniere"},
    {id:"m13", n:13, title:"Il Basilisco",             type:"kills_name",  target:1,   enemy:"Basilisco",             desc:"Sconfiggi il Basilisco"},
    {id:"m14", n:14, title:"Esploratore Profondo",     type:"spedizioni",  target:10,  desc:"Esegui 10 spedizioni nelle Miniere"},
    {id:"m15", n:15, title:"Il Drago delle Cave",      type:"kills_name",  target:1,   enemy:"Giovane Drago di Pietra",desc:"Sconfiggi il Giovane Drago di Pietra"},
    {id:"m16", n:16, title:"Ricchezze Sotterranee",    type:"denari_area", target:1000,desc:"Accumula 1000 denari da bottini delle Miniere"},
    {id:"m17", n:17, title:"Lo Stregone Nano",         type:"kills_name",  target:1,   enemy:"Stregone Nano",         desc:"Sconfiggi lo Stregone Nano"},
    {id:"m18", n:18, title:"Il Guardiano Golem",       type:"kills_name",  target:1,   enemy:"Guardiano Golem",       desc:"Sconfiggi il Guardiano Golem"},
    {id:"m19", n:19, title:"Veterano delle Profondità",type:"spedizioni",  target:15,  desc:"Esegui 15 spedizioni nelle Miniere"},
    {id:"m20", n:20, title:"Il Re delle Miniere",      type:"kills_name",  target:1,   enemy:"Nano Re delle Miniere", desc:"Sconfiggi il Nano Re delle Miniere", sblocca:"isole"},
  ],

  isole: [
    {id:"i01", n:1,  title:"Approdo Maledetto",       type:"spedizioni",  target:1,   desc:"Prima spedizione nelle Isole dei Naufraghi"},
    {id:"i02", n:2,  title:"Granchi e Fantasmi",      type:"kills_area",  target:6,   desc:"Uccidi 6 nemici delle Isole"},
    {id:"i03", n:3,  title:"Silenzio delle Sirene",   type:"kills_name",  target:3,   enemy:"Sirena Predatrice",    desc:"Sconfiggi 3 Sirene Predatrici"},
    {id:"i04", n:4,  title:"Perle del Mare",          type:"loot_area",   target:3,   desc:"Ottieni 3 oggetti dalle Isole"},
    {id:"i05", n:5,  title:"Navigatore Coraggioso",   type:"spedizioni",  target:3,   desc:"Esegui 3 spedizioni nelle Isole"},
    {id:"i06", n:6,  title:"Tentacoli nell'Ombra",    type:"kills_name",  target:4,   enemy:"Polpo di Scogliera",   desc:"Sconfiggi 4 Polpi di Scogliera"},
    {id:"i07", n:7,  title:"Vichinghi dei Mari",      type:"kills_name",  target:3,   enemy:"Guerriero Vichingo",   desc:"Sconfiggi 3 Guerrieri Vichinghi"},
    {id:"i08", n:8,  title:"Bottino del Naufragio",   type:"denari_area", target:600, desc:"Accumula 600 denari da bottini delle Isole"},
    {id:"i09", n:9,  title:"L'Idra Marina",           type:"kills_name",  target:1,   enemy:"Idra Marina",          desc:"Sconfiggi l'Idra Marina"},
    {id:"i10", n:10, title:"Lupo di Mare",            type:"spedizioni",  target:5,   desc:"Esegui 5 spedizioni nelle Isole"},
    {id:"i11", n:11, title:"Spiriti dell'Oceano",     type:"kills_name",  target:3,   enemy:"Elementale d'Acqua",   desc:"Sconfiggi 3 Elementali d'Acqua"},
    {id:"i12", n:12, title:"Seta di Sirena",          type:"loot_area",   target:5,   desc:"Ottieni 5 oggetti dalle Isole"},
    {id:"i13", n:13, title:"Il Capitano Spettrale",   type:"kills_name",  target:1,   enemy:"Capitano Spettrale",   desc:"Sconfiggi il Capitano Spettrale"},
    {id:"i14", n:14, title:"Esploratore dei Mari",    type:"spedizioni",  target:10,  desc:"Esegui 10 spedizioni nelle Isole"},
    {id:"i15", n:15, title:"Il Drago del Mare",       type:"kills_name",  target:1,   enemy:"Drago Marino Antico",  desc:"Sconfiggi il Drago Marino Antico"},
    {id:"i16", n:16, title:"Tesori Sommersi",         type:"denari_area", target:2000,desc:"Accumula 2000 denari da bottini delle Isole"},
    {id:"i17", n:17, title:"Il Re dei Tritoni",       type:"kills_name",  target:1,   enemy:"Re dei Tritoni",       desc:"Sconfiggi il Re dei Tritoni"},
    {id:"i18", n:18, title:"Il Guardiano di Corallo", type:"kills_name",  target:1,   enemy:"Colosso di Corallo",   desc:"Sconfiggi il Colosso di Corallo"},
    {id:"i19", n:19, title:"Capitano dei Mari",       type:"spedizioni",  target:15,  desc:"Esegui 15 spedizioni nelle Isole"},
    {id:"i20", n:20, title:"Il Re del Mare",          type:"kills_name",  target:1,   enemy:"Re del Mare",          desc:"Sconfiggi il Re del Mare", sblocca:"montagne"},
  ],

  montagne: [
    {id:"mo01", n:1,  title:"Vetta Proibita",           type:"spedizioni",  target:1,   desc:"Prima spedizione nelle Montagne Silenti"},
    {id:"mo02", n:2,  title:"Bestie del Ghiaccio",      type:"kills_name",  target:3,   enemy:"Yeti",                  desc:"Uccidi 3 Yeti"},
    {id:"mo03", n:3,  title:"Goblin d'Alta Quota",      type:"kills_name",  target:5,   enemy:"Goblin di Montagna",    desc:"Uccidi 5 Goblin di Montagna"},
    {id:"mo04", n:4,  title:"Piume del Vento",          type:"loot_area",   target:3,   desc:"Ottieni 3 oggetti dalle Montagne"},
    {id:"mo05", n:5,  title:"Scalatore Temerario",      type:"spedizioni",  target:3,   desc:"Esegui 3 spedizioni nelle Montagne"},
    {id:"mo06", n:6,  title:"L'Aquila Gigante",         type:"kills_name",  target:3,   enemy:"Aquila Gigante",        desc:"Sconfiggi 3 Aquile Giganti"},
    {id:"mo07", n:7,  title:"Spiriti del Vento",        type:"kills_name",  target:3,   enemy:"Elementale del Vento",  desc:"Sconfiggi 3 Elementali del Vento"},
    {id:"mo08", n:8,  title:"Oro delle Vette",          type:"denari_area", target:1000,desc:"Accumula 1000 denari da bottini delle Montagne"},
    {id:"mo09", n:9,  title:"Il Ciclope",               type:"kills_name",  target:1,   enemy:"Ciclope",               desc:"Sconfiggi il Ciclope"},
    {id:"mo10", n:10, title:"Conquistatore delle Vette",type:"spedizioni",  target:5,   desc:"Esegui 5 spedizioni nelle Montagne"},
    {id:"mo11", n:11, title:"I Giganti della Roccia",   type:"kills_name",  target:2,   enemy:"Guerriero Gigante",     desc:"Sconfiggi 2 Guerrieri Giganti"},
    {id:"mo12", n:12, title:"Cristallo della Tempesta", type:"loot_area",   target:5,   desc:"Ottieni 5 oggetti dalle Montagne"},
    {id:"mo13", n:13, title:"La Strega del Gelo",       type:"kills_name",  target:1,   enemy:"Strega del Gelo",       desc:"Sconfiggi la Strega del Gelo"},
    {id:"mo14", n:14, title:"Esploratore delle Vette",  type:"spedizioni",  target:10,  desc:"Esegui 10 spedizioni nelle Montagne"},
    {id:"mo15", n:15, title:"Il Drago delle Nevi",      type:"kills_name",  target:1,   enemy:"Drago delle Nevi",      desc:"Sconfiggi il Drago delle Nevi"},
    {id:"mo16", n:16, title:"Ricchezze della Vetta",    type:"denari_area", target:3000,desc:"Accumula 3000 denari da bottini delle Montagne"},
    {id:"mo17", n:17, title:"Il Gigante di Fuoco",      type:"kills_name",  target:1,   enemy:"Gigante di Fuoco",      desc:"Sconfiggi il Gigante di Fuoco"},
    {id:"mo18", n:18, title:"Il Drago Antico",          type:"kills_name",  target:1,   enemy:"Drago Antico della Vetta",desc:"Sconfiggi il Drago Antico della Vetta"},
    {id:"mo19", n:19, title:"Veterano delle Vette",     type:"spedizioni",  target:15,  desc:"Esegui 15 spedizioni nelle Montagne"},
    {id:"mo20", n:20, title:"Il Padre Cade",            type:"kills_name",  target:1,   enemy:"Padre dei Giganti",     desc:"Sconfiggi il Padre dei Giganti", sblocca:"deserto"},
  ],

  deserto: [
    {id:"d01", n:1,  title:"Bruciati dalla Sabbia",    type:"spedizioni",  target:1,   desc:"Prima spedizione nel Deserto delle Ossa"},
    {id:"d02", n:2,  title:"Veleno nel Sangue",        type:"kills_name",  target:3,   enemy:"Scorpione del Deserto", desc:"Uccidi 3 Scorpioni del Deserto"},
    {id:"d03", n:3,  title:"Mummie sul Cammino",       type:"kills_name",  target:3,   enemy:"Guerriero Mummia",      desc:"Sconfiggi 3 Guerrieri Mummia"},
    {id:"d04", n:4,  title:"Oro della Sabbia",         type:"loot_area",   target:3,   desc:"Ottieni 3 oggetti dal Deserto"},
    {id:"d05", n:5,  title:"Perso nel Deserto",        type:"spedizioni",  target:3,   desc:"Esegui 3 spedizioni nel Deserto"},
    {id:"d06", n:6,  title:"Il Djinn del Deserto",     type:"kills_name",  target:2,   enemy:"Djinn del Deserto",     desc:"Sconfiggi 2 Djinn del Deserto"},
    {id:"d07", n:7,  title:"Tempeste di Sabbia",       type:"kills_name",  target:3,   enemy:"Elementale di Sabbia",  desc:"Sconfiggi 3 Elementali di Sabbia"},
    {id:"d08", n:8,  title:"Oro del Faraone",          type:"denari_area", target:1500,desc:"Accumula 1500 denari da bottini del Deserto"},
    {id:"d09", n:9,  title:"La Sfinge",                type:"kills_name",  target:1,   enemy:"Sfinge",                desc:"Sconfiggi la Sfinge"},
    {id:"d10", n:10, title:"Sopravvissuto del Deserto",type:"spedizioni",  target:5,   desc:"Esegui 5 spedizioni nel Deserto"},
    {id:"d11", n:11, title:"Guardiani della Cripta",   type:"kills_name",  target:2,   enemy:"Guardiano della Cripta",desc:"Sconfiggi 2 Guardiani della Cripta"},
    {id:"d12", n:12, title:"Amuleto Sacro",            type:"loot_area",   target:5,   desc:"Ottieni 5 oggetti dal Deserto"},
    {id:"d13", n:13, title:"La Manticora",             type:"kills_name",  target:1,   enemy:"Manticora",             desc:"Sconfiggi la Manticora"},
    {id:"d14", n:14, title:"Esploratore delle Dune",   type:"spedizioni",  target:10,  desc:"Esegui 10 spedizioni nel Deserto"},
    {id:"d15", n:15, title:"Il Drago della Tempesta",  type:"kills_name",  target:1,   enemy:"Drago della Tempesta",  desc:"Sconfiggi il Drago della Tempesta"},
    {id:"d16", n:16, title:"Tesori Eterni",            type:"denari_area", target:5000,desc:"Accumula 5000 denari da bottini del Deserto"},
    {id:"d17", n:17, title:"Il Djinn Imperiale",       type:"kills_name",  target:1,   enemy:"Djinn Imperiale",       desc:"Sconfiggi il Djinn Imperiale"},
    {id:"d18", n:18, title:"Il Custode della Piramide",type:"kills_name",  target:1,   enemy:"Custode della Piramide",desc:"Sconfiggi il Custode della Piramide"},
    {id:"d19", n:19, title:"Veterano del Deserto",     type:"spedizioni",  target:15,  desc:"Esegui 15 spedizioni nel Deserto"},
    {id:"d20", n:20, title:"Il Re Eterno",             type:"kills_name",  target:1,   enemy:"Faraone Non-Morto",     desc:"Sconfiggi il Faraone Non-Morto", sblocca:"oltretomba"},
  ],

  oltretomba: [
    {id:"o01", n:1,  title:"Oltre la Soglia",          type:"spedizioni",  target:1,   desc:"Prima spedizione nell'Oltretomba"},
    {id:"o02", n:2,  title:"Anime Perdute",            type:"kills_name",  target:5,   enemy:"Anima Perduta",         desc:"Sconfiggi 5 Anime Perdute"},
    {id:"o03", n:3,  title:"Guardie dei Morti",        type:"kills_name",  target:3,   enemy:"Guardia dei Morti",     desc:"Sconfiggi 3 Guardie dei Morti"},
    {id:"o04", n:4,  title:"Monete di Caronte",        type:"loot_area",   target:5,   desc:"Ottieni 5 oggetti dall'Oltretomba"},
    {id:"o05", n:5,  title:"Discesa nell'Abisso",      type:"spedizioni",  target:3,   desc:"Esegui 3 spedizioni nell'Oltretomba"},
    {id:"o06", n:6,  title:"Il Drago Non-Morto",       type:"kills_name",  target:1,   enemy:"Drago Non-Morto",       desc:"Sconfiggi il Drago Non-Morto"},
    {id:"o07", n:7,  title:"Demoni nell'Oscurità",     type:"kills_name",  target:3,   enemy:"Demone Minore",         desc:"Sconfiggi 3 Demoni Minori"},
    {id:"o08", n:8,  title:"Oro dell'Aldilà",          type:"denari_area", target:3000,desc:"Accumula 3000 denari da bottini dell'Oltretomba"},
    {id:"o09", n:9,  title:"Il Cavaliere Senza Testa", type:"kills_name",  target:1,   enemy:"Cavaliere Senza Testa", desc:"Sconfiggi il Cavaliere Senza Testa"},
    {id:"o10", n:10, title:"Non si Muore qui",         type:"spedizioni",  target:5,   desc:"Esegui 5 spedizioni nell'Oltretomba"},
    {id:"o11", n:11, title:"Il Gran Lich",             type:"kills_name",  target:1,   enemy:"Gran Lich",             desc:"Sconfiggi il Gran Lich"},
    {id:"o12", n:12, title:"Reliquie Infernali",       type:"loot_area",   target:5,   desc:"Ottieni 5 oggetti dall'Oltretomba"},
    {id:"o13", n:13, title:"Il Principe Demone",       type:"kills_name",  target:1,   enemy:"Principe Demone",       desc:"Sconfiggi il Principe Demone"},
    {id:"o14", n:14, title:"Signore dell'Aldilà",      type:"spedizioni",  target:10,  desc:"Esegui 10 spedizioni nell'Oltretomba"},
    {id:"o15", n:15, title:"Il Signore dei Demoni",    type:"kills_name",  target:1,   enemy:"Signore dei Demoni",    desc:"Sconfiggi il Signore dei Demoni"},
    {id:"o16", n:16, title:"Tesori dell'Eternità",     type:"denari_area", target:10000,desc:"Accumula 10000 denari da bottini dell'Oltretomba"},
    {id:"o17", n:17, title:"L'Incarnazione",           type:"kills_name",  target:1,   enemy:"Incarnazione della Morte",desc:"Sconfiggi l'Incarnazione della Morte"},
    {id:"o18", n:18, title:"Il Colosso delle Anime",   type:"kills_name",  target:1,   enemy:"Colosso delle Anime",   desc:"Sconfiggi il Colosso delle Anime"},
    {id:"o19", n:19, title:"Eterno Guerriero",         type:"spedizioni",  target:15,  desc:"Esegui 15 spedizioni nell'Oltretomba"},
    {id:"o20", n:20, title:"Il Divoratore",            type:"kills_name",  target:1,   enemy:"Il Divoratore",         desc:"Sconfiggi Il Divoratore", sblocca:"empireo"},
  ],

  empireo: [
    // 10 uccisioni singole (una per dio)
    {id:"emp01", n:1,  title:"La Caduta di Valeska",  type:"kills_god",  target:1, godId:"e181", desc:"Sconfiggi Valeska — scomparirà per sempre", trophy:true},
    {id:"emp02", n:2,  title:"La Caduta di Thalmos",  type:"kills_god",  target:1, godId:"e182", desc:"Sconfiggi Thalmos — scomparirà per sempre", trophy:true},
    {id:"emp03", n:3,  title:"La Caduta di Sylvaris", type:"kills_god",  target:1, godId:"e183", desc:"Sconfiggi Sylvaris — scomparirà per sempre", trophy:true},
    {id:"emp04", n:4,  title:"La Caduta di Ignaroth", type:"kills_god",  target:1, godId:"e184", desc:"Sconfiggi Ignaroth — scomparirà per sempre", trophy:true},
    {id:"emp05", n:5,  title:"La Caduta di Abyssor",  type:"kills_god",  target:1, godId:"e185", desc:"Sconfiggi Abyssor — scomparirà per sempre", trophy:true},
    {id:"emp06", n:6,  title:"La Caduta di Lunarys",  type:"kills_god",  target:1, godId:"e186", desc:"Sconfiggi Lunarys — scomparirà per sempre", trophy:true},
    {id:"emp07", n:7,  title:"La Caduta di Solarius", type:"kills_god",  target:1, godId:"e187", desc:"Sconfiggi Solarius — scomparirà per sempre", trophy:true},
    {id:"emp08", n:8,  title:"La Caduta di Varos",    type:"kills_god",  target:1, godId:"e188", desc:"Sconfiggi Varos — scomparirà per sempre", trophy:true},
    {id:"emp09", n:9,  title:"La Caduta di Morvath",  type:"kills_god",  target:1, godId:"e189", desc:"Sconfiggi Morvath — scomparirà per sempre", trophy:true},
    {id:"emp10", n:10, title:"La Caduta di Kaelos",   type:"kills_god",  target:1, godId:"e190", desc:"Sconfiggi Kaelos — scomparirà per sempre", trophy:true},
    // missione finale
    {id:"emp11", n:11, title:"L'Empireo è Caduto",    type:"kills_all_gods", target:10, desc:"Sconfiggi tutte e 10 le divinità dell'Empireo — missione finale di KAIZEN", trophy:true, final:true},
    // 10 raccolte divine
    {id:"emp12", n:12, title:"Il Dono di Valeska",   type:"loot_god", target:1, godId:"e181", lootId:"gl01", desc:"Ottieni le Lacrime di Valeska"},
    {id:"emp13", n:13, title:"Il Dono di Thalmos",   type:"loot_god", target:1, godId:"e182", lootId:"gl02", desc:"Ottieni il Frammento della Mente di Thalmos"},
    {id:"emp14", n:14, title:"Il Dono di Sylvaris",  type:"loot_god", target:1, godId:"e183", lootId:"gl03", desc:"Ottieni la Freccia di Sylvaris"},
    {id:"emp15", n:15, title:"Il Dono di Ignaroth",  type:"loot_god", target:1, godId:"e184", lootId:"gl04", desc:"Ottieni la Cenere di Ignaroth"},
    {id:"emp16", n:16, title:"Il Dono di Abyssor",   type:"loot_god", target:1, godId:"e185", lootId:"gl05", desc:"Ottieni la Goccia dell'Abisso"},
    {id:"emp17", n:17, title:"Il Dono di Lunarys",   type:"loot_god", target:1, godId:"e186", lootId:"gl06", desc:"Ottieni la Scheggia di Luna"},
    {id:"emp18", n:18, title:"Il Dono di Solarius",  type:"loot_god", target:1, godId:"e187", lootId:"gl07", desc:"Ottieni il Raggio Solidificato"},
    {id:"emp19", n:19, title:"Il Dono di Varos",     type:"loot_god", target:1, godId:"e188", lootId:"gl08", desc:"Ottieni la Lama Spezzata di Varos"},
    {id:"emp20", n:20, title:"Il Dono di Morvath",   type:"loot_god", target:1, godId:"e189", lootId:"gl09", desc:"Ottieni il Velo di Morvath"},
    {id:"emp21", n:21, title:"Il Dono di Kaelos",    type:"loot_god", target:1, godId:"e190", lootId:"gl10", desc:"Ottieni la Clessidra di Kaelos"},
  ],
};
